### ISSUE TITLE
Trigger theme previews on click

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#10]
Hey @FrancescoSTL,

I was looking over the code to preview the various themes, and I am wondering, any specific need we are doing this on hover as apposed to on click?

There is a couple of benefits to using click as apposed to hover as well:

1. The code at the moment feels way more complex that it needs to be. There is some tweaking we can do to improve this but, switching to click will just remove all that complexity.
2. A user's natural tendency will be to click the buttons presented. This might very well lead to an impression that the functionality is broken. The reason I state this is because, unless the user is on a fast connection(something we cannot assume), the preview will surely not be downloaded and activated in the time it takes to mousein, click and mouseout. 
3. Whether or not we go with click or hover, we need to provide some feedback to the user that their action has triggered a response that is still being processed. A simple little loader will work perfectly fine here.
4. In terms of applying or merely previewing a theme. Seeing that both requires one to first get the theme, we can just assume apply, and leave the theme applied unless the user explicitly clicks on the 'Reset to default' link/button.

Let me know your thoughts on this. Thanks!

**Comment by FrancescoSTL** [comment]
When speaking with @chrismore, the idea behind hover was to mimic the functionality on https://addons.mozilla.org/en-US/firefox/themes/. I agree that the code seems fairly complex. This was a result of issues regarding fast mouse movement and the mouseleave function not being triggered. It is a fairly documented issue online, so it doesn't seem to be isolated with this project.

If we want to adopt clicking vs hover, I am fine with ditching the logic existing. I agree that hover is mildly clunky, esp if the user is on a slow connection, however, it might be more clear what the sidebar is actually asking the user to do.

Thoughts @chrismore @schalkneethling?

**Comment by chrismore** [comment]
We were trying to mimic the theme preview from AMO. Yes, it is more complex than click.

**Comment by chrismore** [comment]
Maybe the hover isn't worth it.... hmm

**Comment by chrismore** [comment]
The preview may not be apparent to users and they may click as fast as they would potentially hover and not click.

**Comment by chrismore** [comment]
@FrancescoSTL @schalkneethling let's just eliminate the mouse over and just do a onClick apply of the theme. AMO doesn't have a "reset to default" link, which is why they probably did the mouse over so a mouse over for us doesn't seem to provide much benefit. Without the benefit, we are just making the code more complex.

**Comment by FrancescoSTL** [comment]
This thread can be closed upon successful merge of https://github.com/mozilla/all-aboard/pull/26.

**Comment by FrancescoSTL** [comment]
Merged
