### ISSUE TITLE
Sun in vales sidebar content 2 icon is not animating

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#100]
Currently, there is no animation.

**Comment by schalkneethling** [comment]
I cannot replicate this one. With that said, whilst testing earlier on, it seemed like the browser had some painting issues that caused the gif animation to appear broken. We really need to look at optimizing these.

**Comment by FrancescoSTL** [comment]
Might be an issue locally on my machine. I redownloaded the gif and it was animated, however, ran a git diff and there was no difference.

**Comment by schalkneethling** [comment]
![sidebar2](https://cloud.githubusercontent.com/assets/10350960/16113904/e5cc3d86-33be-11e6-8653-b43f6f2d1a5b.gif)

@FrancescoSTL no, I think these gif animations are causing problems. They are heavy on the computers cpu, and once the browser is suffering, it effects all follow up sidebars as well.

**Comment by schalkneethling** [comment]
I am closing this for now, we ca reopen if we still see this after the gifs have been optimized.
