### ISSUE TITLE
CSS disable the wrong answers on the values track after clicking "Tell Me"

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#101]
After clicking tell me:

* radio buttons are disabled
* wrong answers are greyed out
* correct answer is bold

**Comment by FrancescoSTL** [comment]
Finished disabling answers and merged in #128. Next- grey out the wrong answers

**Comment by schalkneethling** [comment]
> wrong answers are greyed out

@chrismore Do we still want to this?

**Comment by chrismore** [comment]
@schalkneethling Right now @FrancescoSTL has it bolding and radio buttons disabled and that should be fine. Given that we are saying something funny for each response and people may want to re-read them, let's skip the grey out the wrong answers. Let's call this issue closed and move on to other issues.
