### ISSUE TITLE
Radio buttons over A/B/C text labels

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#11]
Hey @chrismore,

I have followed some of the discussion regarding the switch from radio buttons to A/B/C text labels, and it seems that there is a consensus to switch back to radio buttons. Is my understanding correct here?

If so, then I have a follow on question. Seeing that a user will now be able to select an answer, I guess we want to amend the interaction a bit. So currently, when the user clicks "Show me/Tell me", we simply highlight the correct answer.

With the radio button interaction do we want to:

1. Simply highlight the correct answer (radio button only, or perhaps highlight the text - Perhaps Matt has some suggestions here) upon clicking the button or,
2. Do we want to first check whether the user have selected the correct answer and if not, highlight the answer they gave as red(incorrect) and they can have another go or,
3. Highlight the users answer in red if incorrect but, also highlight the correct answer in green.

Thanks!

**Comment by chrismore** [comment]
@schalkneethling probably option 1 or 3. We want to make this pretty simply and we don't need to quiz people again if they didn't get it right. 95% of the time, people will probably get it right the first try. There is really only one obvious answer.

How about this option 4:

* Regardless if a user selects any of the radio buttons or not, when they click the "Tell Me" button, we highlight the correct answer in green. If they select the wrong one, we don't do anything different. If they select no answers and click "Tell Me", we again show the answers. Basically, radio buttons are not functional. We tell people the correct answer regardless if they got it right or wrong and we tell them the answer. We don't have to make people feel stupid if they get the wrong answer and we want to make it very simple. No form validation or required fields. Just don't have any radio buttons defaulted.

How's that sound?

**Comment by FrancescoSTL** [comment]
@chrismore++

I like option 4. Providing negative feedback if the user gets an answer wrong, might give off a negative vibe, and I think the point of the sidebar is to simply provide information rather than truly quiz users.

**Comment by schalkneethling** [comment]
@chrismore Option 4 sounds fine but, I do not really understand why we need to use radio buttons at all then. Just so the user has the option to select something? Kinda faux interaction ;)

**Comment by chrismore** [comment]
@schalkneethling re: radio buttons. Yeah, they are really faux. The issue with making them not radio button (how they were designed) is that it sort of looks like they should be clickable, but they are not. Imagine a user trying to click them and think they are broken and then maybe answer the question. The radio buttons just provide feedback to the user that they have select an answer and that they can click submit. But if they click submit without selecting something, we'll just tell them the answer.

**Comment by FrancescoSTL** [comment]
Merged
