### ISSUE TITLE
Get Firefox on your phone

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#12]
@chrismore 

For the "Get Firefox on your phone" button, I assume we will be sending users to https://www.mozilla.org/firefox/mobile-download/ in a new tab?

**Comment by chrismore** [comment]
@schalkneethling it should be the two mobile app store buttons stacked vertically using buttons from here:

https://www.mozilla.org/en-US/firefox/new/?scene=2

Here are custom URLs for them:

Google Play store url:

https://play.google.com/store/apps/details?id=org.mozilla.firefox&referrer=utm_source=firefox-browser&utm_medium=Referral&utm_campaign=onboarding-addon

Apple App store url:

https://itunes.apple.com/us/app/apple-store/id989804926?pt=373246&mt=8&ct=firefox-onboarding-addon

**Comment by FrancescoSTL** [comment]
This issue can be closed after successful merge of #35

**Comment by chrismore** [comment]
Merged #35
