### ISSUE TITLE
Check Distribution.id before appending values

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#123]
If you install the add-on, answer the questions, use the answers, then re-install the add-on, and go through the experience again, it will keep appending the meta data to the distribution.id over and over.

mozilla86-utility-new-values-existing-utility-existing-new......

**Comment by schalkneethling** [comment]
@chrismore I wonder if this is still an issue. When https://github.com/mozilla/all-aboard/pull/219 merges, the user will never again be prompted with the questions on firstrun unless they use a completely new profile. If they do however, I reckon the `distribution.id` would be reset to it's original and will not retain the value from the previous session/profile.

**Comment by schalkneethling** [comment]
@chrismore So, I was wondering about this one. It is going to be kinda tricky to check whether a specific combination of the new/existing and utility/values strings are in the distribution.id (there are essentially 4 possible combinations).

I was therefore thinking that, the default length of distribution.id will be 9 characters (mozilla86) so, if the string is longer than 9, we have already updated it with the track and user status so, the only thing we want to change is the step number.

Therefore if the length is longer than 9 and the value passed cannot be parsed to an int, do nothing else, update the step(https://github.com/mozilla/all-aboard/blob/master/lib/utils.js#L31). Does that make sense?

**Comment by chrismore** [comment]
@schalkneethling I think the >9 characters in the distribution.id, don't append values is a simple solution here that will handle it. We do append multiple values to it, we do it once after the questions. After that point, it is just updating the step at the end.

**Comment by chrismore** [comment]
and the step is a regex replace, so we should be fine.

**Comment by schalkneethling** [comment]
Agreed, thx @chrismore

**Comment by FrancescoSTL** [comment]
Fixed in #252
