### ISSUE TITLE
Randomize "do it yourself" vs "do good"

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#125]
Per Ben/Fabio, we'd like to randomize the order of "do it yourself" vs "do good" on the firstrun page.

**Comment by chrismore** [comment]
Great idea. Let's do it so it doesn't influence the selection.

**Comment by FrancescoSTL** [comment]
Can close on merge of #193

**Comment by groovenectar** [comment]
I have to ask, I may be out of the loop. From my first exposure -- What the hell kind of question is this? What is the point of asking it? There is no option for both? I had not seen this Q&A thing on first install before. Where does this question come from, and what is the point of it? I was tempted to uninstall Firefox as soon as I saw that. How is it not stupid -- or -- what exactly is it for?

I can see where "Have you used Firefox in the last 30 days?" is really not stupid. Firefox is installed on my machine now and it is creeping me out.

**Comment by jaxx0rr** [comment]
better yet.. put some description under each choice so we know what the fuk it implies.. Firefox was once a good browser and I've used it for php development since 2001 but think its become stale ...
