### ISSUE TITLE
Make sidebar HTML/CSS responsive

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#127]
We are still getting some horizontal scrolling and even with making the margins smaller, we are going to be optimizing for a fixed resolution when we have users on a variety of screen sizes. So, let's see what we can do to make the sidebar responsive. We'll need this by the end of the month.

**Comment by chrismore** [comment]
I will drop in the top resolutions for the top 90% of resolutions for this experiment.

Target: Firefox + First Run + English + US + Windows

**Comment by chrismore** [comment]
Here's the top 90% of resolutions that we need to consider to keep the sidebar from horizontal scrolling

1. 1366x768
(25.23%)

2. 1920x1080
(19.98%)

3. 1600x900
(9.45%)

4. 1280x1024
(7.42%)

5. 1536x864
(5.83%)

6. 1024x768
(4.63%)

7. 1440x900
(4.61%)

8. 1680x1050
(3.75%)

9. 1280x720
(3.64%)

10. 1280x800
(2.36%)

11. 1920x1200
(1.68%)

12. 800x600
(1.30%)

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL Here's the resolutions.

**Comment by chrismore** [comment]
The percentages represent the percentage of all users who will see the experiment.

**Comment by chrismore** [comment]
We can probably drop 800x600 support as it is 1.3%

**Comment by chrismore** [comment]
We need to make the sidebar work at a screen resolution of 768 pixels and remember that is not viewport size.

**Comment by chrismore** [comment]
I will find out the viewport size for 768 resolution screens with Firefox's chrome size *if* Firefox is maximized.

**Comment by chrismore** [comment]
Firefox's browser chrome is 80 pixels high. So, 768 - 80 = 688 viewport size.

**Comment by chrismore** [comment]
Looks like the utility path fits except for the themes, but we can file an issue to remove a theme button.

![screen shot 2016-06-28 at 9 10 45 pm](https://cloud.githubusercontent.com/assets/751491/16440293/5e2fb888-3d75-11e6-97e1-5abc9a6b4ba5.png)

![screen shot 2016-06-28 at 9 11 20 pm](https://cloud.githubusercontent.com/assets/751491/16440295/63cecc70-3d75-11e6-8bf7-32098eeb845b.png)

![screen shot 2016-06-28 at 9 12 19 pm](https://cloud.githubusercontent.com/assets/751491/16440299/6828d2fc-3d75-11e6-8986-a7cf45868948.png)

**Comment by chrismore** [comment]
Filed issue #195 to remove a theme button and it may barely fit.

**Comment by chrismore** [comment]
The values side is not looking good for being able to fit. Basically, anytime we have an additional follow up, we run out of vertical room.

![screen shot 2016-06-28 at 9 22 53 pm](https://cloud.githubusercontent.com/assets/751491/16440525/8e71b97c-3d77-11e6-91c9-85ca9c818182.png)

![screen shot 2016-06-28 at 9 23 31 pm](https://cloud.githubusercontent.com/assets/751491/16440527/92b40468-3d77-11e6-9479-ca6264173240.png)

![screen shot 2016-06-28 at 9 24 03 pm](https://cloud.githubusercontent.com/assets/751491/16440529/9711317a-3d77-11e6-8215-bd5f75af3595.png)

![screen shot 2016-06-28 at 9 27 23 pm](https://cloud.githubusercontent.com/assets/751491/16440531/9aef6672-3d77-11e6-8006-e7045ed569a3.png)

![screen shot 2016-06-28 at 9 28 46 pm](https://cloud.githubusercontent.com/assets/751491/16440532/9eaa3f80-3d77-11e6-9b6e-4aa658bfb446.png)

We may have to remove the follow up items on a few of the values sidebars. Also, since we don't have follow ups on all of them, maybe it is best we keep it simple on values.

**Comment by chrismore** [comment]
What does everyone think about:

1) Remove the private browsing mode copy and button on content 3 on values

2) Remove the link to the smarton page on content 4 on values

3) Remove most of the padding after the question and the bullets on values to shift the questions up

4) Reduce the padding above the tokens by 50%

**Comment by FrancescoSTL** [comment]
@chrismore would each of those options provide a solution individually, or cumulatively?

**Comment by chrismore** [comment]
@FrancescoSTL cumulatively -- all of those together should make the values track barely fit and the utility track will have some additional space. 

True, we could just make the header image smaller, but I don't think that alone will make this work without losing the visual impact of the header images.

**Comment by fabiorios** [comment]
@chrismore we should try and keep the secondary CTAs - private browsing and smarton. (only because we spent so much time on it ;)

The orphaned words are taking up too much space. If we modify the text slightly we can save <br>. Combined with padding, we should be fine. Maybe a quick screen share session with @FrancescoSTL and we can fix today?

Here's an example:

![noorphans](https://cloud.githubusercontent.com/assets/19597198/16458361/ac14427c-3dd3-11e6-9d81-ee386f2355ea.JPG)

**Comment by chrismore** [comment]
@fabiorios we have spent lots of time on the questions and answers and very little time on the follow ups. Actually, Eric never really was a fan of the follow ups on the values side and it is asking for quite a bit to answer a question and then perform some other action. Even though, I am a fan of these specific follow ups, we are out of space and we have to make a decision about what is more import.

What I don't want to do is play with the Q&A copy that we have already spent so many hours nailing down and getting approval. We can easily modify the follow up copy and play with the padding and see if we can make it there.

We could:

* reduce padding above header image (we can probably get closer to the top [x] bar because there is nothing up there and gives the illusion of more padding)
* reduce padding below header image
* reduce padding below question and above answers
* reduce padding above the tokens
* Shorten the follow up copy as much as possible (e.g. No other browsers gives you so much control)

**Comment by fabiorios** [comment]
@chrismore true, most important is to not change the question copy.

Now that you've said that about the follow-up ctas, I'm changing my vote to remove them. I see it. Value is delivered with the questions, not the follow-up. I'm good with you proposal:

1) Remove the private browsing mode copy and button on content 3 on values
2) Remove the link to the smarton page on content 4 on values
3) Remove most of the padding after the question and the bullets on values to shift the questions up
4) Reduce the padding above the tokens by 50%

**Comment by chrismore** [comment]
@FrancescoSTL are you taking this one? I can sit next to you when you are making these changes since there are a lot of comments above. Once we the PR, we can drop an image in there for @ternstyles to review.

**Comment by FrancescoSTL** [comment]
@chrismore I can take this today.

**Comment by chrismore** [comment]
@fabiorios we were able to make it all work with adjusting padding and adjusting some of the copy and all of the sidebars now fit. Screenshots coming soon.
