### ISSUE TITLE
Close sidebar w/o recieving token and can't reopen

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#132]
If you open a sidebar and don't finish the main CTA, close the sidebar, then try to reopen it, it will not open up. This is probably due to this line:
https://github.com/mozilla/all-aboard/blob/master/index.js#L583

Where we are checking:
`if( ... && simpleStorage.tokens.length === simpleStorage.step)`

**Comment by schalkneethling** [comment]
I believe this is resolved @chrismore - please confirm using the latest master. Thanks!

**Comment by chrismore** [comment]
@schalkneethling works now!!
