### ISSUE TITLE
Add "introductory" language to the first question

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#133]
Review feedback from Tim:

We need to add a little copy to the first page of first run. This is to give a little more context to what's going on.

The new text should be something like

 "Telling us a little bit about yourself will help Firefox be even better for you"

or

"Knowing about how you use Firefox will help us set you free on the Web."

![screenshot-www mozilla org 2016-06-20 09-50-53](https://cloud.githubusercontent.com/assets/14222130/16196654/c780766a-36cc-11e6-84b2-4f090676a653.png)

**Comment by chrismore** [comment]
How about:

"Help us setup your browser and Firefox will set you free on the Web"

**Comment by chrismore** [comment]
@bniolet1 ?

**Comment by chrismore** [comment]
Moving the "no thanks" link will be handled in issue #148

**Comment by bniolet1** [comment]
@chrismore 

Let's run with it and see how it looks!

>Help us setup your browser and Firefox will set you free on the Web

**Comment by FrancescoSTL** [comment]
merged

**Comment by chrismore** [comment]
Got some feedback on the sentence and need to have it updated.

Old sentence:

Help us setup your browser and Firefox will set you free on the Web

New sentence:

Your Web, your way. Help us set up Firefox just the way you want it.

@FrancescoSTL ping

**Comment by FrancescoSTL** [comment]
@chrismore your wish is my command. Merged in #203
