### ISSUE TITLE
Update copy for the import headline

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#134]
Update the headline on our "Plan B" import wizard page. 
It is currently: 

>In a hurry? 
>We get that. 

It should be: 

>In a hurry?
>We can help.

**Comment by bniolet1** [comment]
![screen shot 2016-06-20 at 10 07 49 am](https://cloud.githubusercontent.com/assets/14222130/16197136/dd85aa3c-36ce-11e6-9b29-879aeaeb55d6.png)

**Comment by FrancescoSTL** [comment]
Fixed in #154
