### ISSUE TITLE
Update copy for the desktop notification window

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#135]
Update copy for the desktop notification that appears when the user has a new message. The text currently reads: 

>All Aboard
>You have a new message

**Comment by bniolet1** [comment]
![screen shot 2016-06-20 at 10 08 23 am](https://cloud.githubusercontent.com/assets/14222130/16197154/f021d7e2-36ce-11e6-9c39-b5c17e83292d.png)

**Comment by chrismore** [comment]
Hmm. What could we say here that is generic, but also going to get users to want to click it.

About about:

Title: Welcome Aboard!
Body: Firefox has something special for you

**Comment by chrismore** [comment]
@bniolet1 ?

**Comment by bniolet1** [comment]
let's make the copy this: 

Title: Welcome Aboard!
Body: Firefox has something special for you.
