### ISSUE TITLE
Add 'Google' as a search option on utility flow #1

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#136]
Comment from Tim: 

We need to add Google as a search option for the utility search pane. Right now, the graphics include Yahoo!, Bing! Amazon!, Duck Duck Go! and Ebay!.

Tim points out that users may think we don't offer Google. Plus Google is featured on the search box (at least on mine where Google is my default search).

![screen shot 2016-06-20 at 10 10 14 am](https://cloud.githubusercontent.com/assets/14222130/16197256/6559342e-36cf-11e6-9ddf-a570d7640d61.png)

**Comment by chrismore** [comment]
![screen shot 2016-06-20 at 11 51 16 am](https://cloud.githubusercontent.com/assets/751491/16206461/7215afe0-36dd-11e6-85c9-a6abc2c665da.png)

**Comment by chrismore** [comment]
We probably still want to stick with 5 icons, so we'll have to drop one:

How about:

[Yahoo] [Google] [Bing] [Amazon] [Duck Duck Go]

@bniolet1  ?

**Comment by bniolet1** [comment]
I'm good with this plan, @chrismore.
