### ISSUE TITLE
Set timers to auto-close sidebars based on some condition

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#137]
Update the logic for the sidebar panel so that if a user does not engage with it for a set time, but has it open, we can consider the user to have engaged with the content and automatically close the sidebar. 

@chrismore My notes are lacking on this one. What did we decide? Detect browsing to a new page determines when to close it? What was the conclusion of this conversation?

**Comment by chrismore** [comment]
How about this logic based on time?

`
if sidebar.open then {

    if sidebar(CTA).interact then {
        settimeout(sidebar.close, 120000)
        // close sidebar 120 seconds after they interact with it.
    } else {
         settimeout(sidebar.close, 300000)
         // close sidebar after 5 minutes if a user doesn't interact with it. Don't give badge and don't start next timer.
    }
}
`

**Comment by chrismore** [comment]
@FrancescoSTL @schalkneethling can you check out this logic to 1) see if it is possible. 2) What you think about the logic.

**Comment by schalkneethling** [comment]
@chrismore so basically, as soon as a sidebar is opened, and the user has not interacted with this sidebar before (this is the first time they are opening it), we start the 5 minute counter. Should the user interact with the CTA before the 5 minutes have elapsed, we cancel the 5min timer, start a 2min timer and close the sidebar.

Obviously then, if the user does not interact with the CTA before 5min has passed, the sidebar closes. Don't pass go, don't collect 200 dollars. We will then however also not start the timer for the next sidebar in the series so, until the user opens the sidebar again and completes the CTA, the on boarding process will be halted at the current step.

**Comment by chrismore** [comment]
@schalkneethling the Firefox team has said they have done a lot of testing with sidebars and other toolbars and after they are open, most users just keep them open and don't realize they can close them and their viewport size is even more compressed. Especially when things open automatically and the first sidebar does. They said we risk having most users just leave it open the whole time and think that is just how Firefox is.

**Comment by chrismore** [comment]
@schalkneethling your assessment above is correct. If the sidebar does auto close and the user doesn't do anything, they are stuck on that step because they never interacted with the CTA. If we really wanted to, we reset the timer on the current sidebar notification until they open it up and interact with it (i.e. every 24 hours), but that seems like it could get spammy quick.

**Comment by schalkneethling** [comment]
Agree, I will implement as in https://github.com/mozilla/all-aboard/issues/137#issuecomment-227777769
