### ISSUE TITLE
Add a link to themes store from utility "customize" panel

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#138]
Add a text link for 

"Explore other themes" to the bottom of the themes panel. 

The link should be: 

https://addons.mozilla.org/en-US/firefox/themes/?utm_source=fdraddon&utm_medium=fdraddon&utm_content=themespanelutil&utm_campaign=fdraddon

@chrismore These utm aren't set in stone of you have hard opinions. Just wanted to be able to track links back to this panel on the add-on.

**Comment by chrismore** [comment]
Given issue #147 that I just created, these URL parameters, should be:

https://addons.mozilla.org/firefox/themes/?utm_source=fxonboarding&utm_medium=referral&utm_campaign=onboardingv1&utm_content=customization

**Comment by FrancescoSTL** [comment]
Donezo
