### ISSUE TITLE
Update copy on utillity mobile sidebar

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#139]
Update copy on mobile sidebar to: 

> Get Firefox on your phone so you can take your history, bookmarks and passwords with you.

**Comment by bniolet1** [comment]
![screen shot 2016-06-20 at 10 30 47 am](https://cloud.githubusercontent.com/assets/14222130/16198014/471842b8-36d2-11e6-95c6-fb07ef16adb9.png)

**Comment by FrancescoSTL** [comment]
Fixed in #155
