### ISSUE TITLE
Sidebar - Utility 1 - Free to choose

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#14]
Sidebar 1 for utility track

## Flow

User clicks on add-on icon
Side bar is opened containing content
User receives the relevant token
User clicks the Try It button
The search box is triggered showing the search providers and search settings panel

**Comment by FrancescoSTL** [comment]
Submitted backend functionality for opening search and switch case statement to catch when to trigger it in https://github.com/mozilla/all-aboard/pull/24.

**Comment by schalkneethling** [comment]
Let close these so we can easily see the overall progress towards v0.5.0
