### ISSUE TITLE
Add 'send to device' link to mobile page

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#141]
Below the app and play store images, please add a text link that says: 

> Send a link to your device. 

The link should be: 

???

@chrismore do we have a single page for all mobile downloads? All is see are separate pages for iOS and Android. I'm worried about the user experience if that's the case. 

https://www.mozilla.org/en-US/firefox/android/

https://www.mozilla.org/en-US/firefox/ios/

**Comment by chrismore** [comment]
Here's the single mobile download page:

https://www.mozilla.org/en-US/firefox/mobile-download/

**Comment by chrismore** [comment]
Let's move this to our next milestone past the MVP. We should do this right and have tracking for the send to device unique to this experience. This is how the about:home experience works and we can duplicate the experience.

**Comment by bniolet1** [comment]
+1. 

Also the single download page doesn't provide any value over just having the badges on the sidebar.
