### ISSUE TITLE
Update copy on Privacy (values) sidebar

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#142]
Update the copy on the values sidebar for privacy. 

![screen shot 2016-06-20 at 10 54 00 am](https://cloud.githubusercontent.com/assets/14222130/16198858/78ea29d4-36d5-11e6-86a8-d636b26369c7.png)

@chrismore 

We need a separate task to update this copy. Answers "B" and "C" need to be shortened and punched up a bit. I can tackle an effort at this.

**Comment by bniolet1** [comment]
task created for this in taiga epic user story for values track

**Comment by bniolet1** [comment]
Answers B and C should be updated to: 

>Tired of seeing the same shoe add on every website. 

>Believes you have the right to not be tracked online.

**Comment by chrismore** [comment]
Short and sweet. Nice job @bniolet1 

+1

**Comment by FrancescoSTL** [comment]
Fixed in #156
