### ISSUE TITLE
When CTA is clicked on the value track, hide "Show answer" button, and display specific copy when question is answered.

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#143]
Right now, showing off the correct answer regardless of whether the user chose correctly or not is a bit of a flat experience. 

We want to punch up the user experience a bit by responding to each answer the user submits. (the fact is, they will see the correct answer and get the point without us having to beat them over the head with the correct answer). 

So the logic / flow is, user selects and answer and we transition to some short text that responds to the answer they chose. We make the CTA button disappear as well. 

We will write text for all of these questions and create a taiga card to track that work.

**Comment by chrismore** [comment]
You can see an example of this change in this mockup.

![image](https://cloud.githubusercontent.com/assets/751491/16246141/c466a7dc-37b8-11e6-973d-1dcaee223bac.png)

**Comment by bniolet1** [comment]
The responses for each answer selection re in the "Response" column here: 

https://docs.google.com/document/d/1Fzxe-Y2ZOheJ0vFFjcQxAiofOWMWgBfjWgeG4gTtP-g/edit#heading=h.s5x6289mcprx

**Comment by chrismore** [comment]
@schalkneethling as mentioned in this PR, use this issue just for the values track. When button clicked, hide button, display specific copy copy in place as seen in this doc in the response column of the values sidebar:

https://docs.google.com/document/d/1Fzxe-Y2ZOheJ0vFFjcQxAiofOWMWgBfjWgeG4gTtP-g/edit#heading=h.s5x6289mcprx

**Comment by schalkneethling** [comment]
@chrismore Do I just use response "C" or do we want to show a response based on the answer the user actually selected? So, if they selected the second answer on content 1, upon clicking "Tell me", will we mark the correct answer, but then the message we show will be "We wish: There’s nothing like flaming desserts."?

Should I completely remove the "Here's your badge!" copy? Or should that follow after the copy above?

**Comment by chrismore** [comment]
@schalkneethling If they select "A", "B", or "C", hide the CTA button, and show the associated response copy in the in-product. Each answer has one and only one response to it. In the in-product copy, @bniolet1 wrote one sentence per each answer to the values track.

@schalkneethling for the "Here's your badge!" you can remove it from this issue and add it to issue #166 which is only about that specific copy across both the values and utility.

**Comment by chrismore** [comment]
All good here now. Nice job!
