### ISSUE TITLE
Tabzilla missing on about:Home

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#145]
This was a comment from Tim. The "mozilla" wordmark on the about:home page is not contained within the tab as it is on our websites. 

I'm personally confused about this since our version is consistent with how about:home currently looks. I will follow up with Tim on this.

**Comment by bniolet1** [comment]
[Mozilla Mail - clarification on add-on feedback.pdf](https://github.com/mozilla/all-aboard/files/323755/Mozilla.Mail.-.clarification.on.add-on.feedback.pdf)

**Comment by bniolet1** [comment]
Update on this: Per Tim, the Mozilla wordmark needs to be the same as the Tabzilla that appears on our webpages. 

<img width="1141" alt="screen shot 2016-06-20 at 11 36 00 am" src="https://cloud.githubusercontent.com/assets/14222130/16201642/5f5c5b08-36e0-11e6-88d7-7fbb3007da1a.png">

**Comment by chrismore** [comment]
We should close this. This is not part of the add-on. Tim should take this up Madhava and the Firefox UX team. about:home is not a webpage.
