### ISSUE TITLE
Add UTM parameters to any external links

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#147]
Let's standardize the UTM parameters in the add-on:

The following should exist on all links:

utm_source=fxonboarding
utm_medium=referral
utm_campaign=onboardingv1

Like:

https://www.mozilla.org/en-US/?utm_source=fxonboarding&utm_medium=referral&utm_campaign=onboardingv1

Then for each link, we can add a specific utm_content field unique to each link:

utm_content=[X] where [X] is the theme of the sidebar, which is what each sidebar is named.

Example full url:

https://www.mozilla.org/about/?utm_source=fxonboarding&utm_medium=referral&utm_campaign=onboardingv1&utm_content=meet-mozilla

This will impact these templates:

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content1-snippet.html

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content2-snippet.html

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content4-snippet.html

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content4.html

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content5-snippet.html

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content5.html

and #138

**Comment by chrismore** [comment]
For links in email, keep all the same parameters as above, but make utm_medium=email instead of referral. cc @bniolet1

**Comment by schalkneethling** [comment]
@chrismore You mention sidebar here:

> utm_content=[X] where [X] is the theme of the sidebar, which is what each sidebar is named.

I am guessing this relates to snippets as well though?

**Comment by chrismore** [comment]
Actually, we probably want to make the utm_medium a bit more specific:

Here's the new format:

All URLs will have:

utm_source=fxonboarding
utm_campaign=onboardingv1

Then each link will be specific to the medium and the content theme.

Example:

email link = utm_medium=email
snippet link = utm_medium=snippet
sidebar link = utm_medium=firefox-browser

content = utm_content = (searching|private browsing|customizing|find your stuff|mobile|organization|mozilla different|security|privacy|community)

So, yes @schalkneethling @bniolet1 it will impact snippets, email and the sidebar external links. Only the values track sidebars and snippets have external links.

**Comment by FrancescoSTL** [comment]
Fixed in #152 

Thanks, @schalkneethling!

**Comment by FrancescoSTL** [comment]
Actually, I'm going to reopen and move to tracking so we can remember to keep doing this if we add other links.

**Comment by schalkneethling** [comment]
Are we aware of any links that current does not have the required parameters?

**Comment by chrismore** [comment]
Looks like we got all of them.
