### ISSUE TITLE
Validate HTML contents in iframe sticker form

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#151]
We should figure out a method to ensure the form that is being presented in the sidebar iframe is what we expected and no one modified the form on ThinkSmart servers. If there is no dynamic content inside the ThinkSmart form, maybe we can hash the value of the HTML to ensure it is exactly the same each time.

**Comment by fabiorios** [comment]
@chrismore they've confirmed:

"And yes, we can certainly support CSRF tokens. We will make this update when we finalize our MSSQL code. Please stay tuned"

**Comment by fabiorios** [comment]
Asked them to reduce form height to fit 220px (including all errors/notifications)

**Comment by FrancescoSTL** [comment]
Blocked by thinkSmart for the CSRF token

**Comment by chrismore** [comment]
Will be handled via ThinkSmart and not the add-on.

**Comment by schalkneethling** [comment]
@chrismore so we can close this one correct?

**Comment by FrancescoSTL** [comment]
Closing via convo w/ @chrismore on slack
