### ISSUE TITLE
Remove sticker form iframe on content 6 sticker offer after offer expiration date

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#157]
The sticker form will close on 9/26/2016. On 9/26/2016, the add-on should replace the iframe to the sticker form to a message saying "We are sorry, but this offer has expired. Thanks for using Firefox and helping fight for a free and open Internet!"

**Comment by FrancescoSTL** [comment]
Will be easier once we can get the iframe hosted on mozilla.org (see #178), as we can simply change the iframe message once the offer is complete.

**Comment by chrismore** [comment]
yeah, I think if we handle this on the heroku page, it will be easier since we can control it on the web instead of the add-on.

**Comment by schalkneethling** [comment]
something we want to keep around @chrismore ?

**Comment by fabiorios** [comment]
@schalkneethling no need to keep this one.

We've dwindled down to 0-4 submissions per day, so no need to cut anyone off. Users can keep submitting the sticker form even through launch of our next version. 

We'll worry about changing/stopping the form at completion of v1.2 funnelcake (sometime in Nov/Dec 2016), only after our contract with ThinkSmart has ended.

@chrismore ^
