### ISSUE TITLE
Add "Claim your prize" link below tokens on content 5 on both tracks

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#158]
We need to add a link to the bottom of content 5 on both tracks to the sticker offer sidebar. This will give people the ability to immediately claim your prize instead of letting them hang.

When content 5 is opened, the timer will start for content 6, the sticker sidebar notification. If a user clicks the "claim your prize" link, it will cancel the timer notification as they are already viewing it. If a user doesn't click "claim your prize" and the notification goes off, a user will be able to engage and open the sticker offer sidebar.

**Comment by chrismore** [comment]
The timer mentioned above is defined in issue #159

**Comment by chrismore** [comment]
![image](https://cloud.githubusercontent.com/assets/751491/16245892/bfc2b906-37b7-11e6-9042-d76889775991.png)
Something Fabio mocked up last week.

**Comment by FrancescoSTL** [comment]
Blocked by #159

**Comment by FrancescoSTL** [comment]
This also needs to trigger a timer for 1/12 of the default time between notifications (2 hours for production)
