### ISSUE TITLE
Decrease interval to content 6 sticker offer sidebar notification

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#159]
We are going to have a final and 6th content sidebar about the sticker offer for those who have received all 5 tokens. We don't want this notification to wait the normal 24 hours as we want to give more instant gratification to what they have accomplished.

We are thinking 2 hours should be suffice for the last notification and to not wait 24 hours. 

To prevent from hard coding 2 hours to the last and 6th sidebar notification, we could just do 1/12th of the current interval. So, with the default 24 hours, it would be set to 2 hours. If we are testing and have it set to 30 seconds, the final offer would happen 2.5 seconds later.

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL is it technically possible to do 1/12 of the interval for the final sticker offer notification regardless of what the normal interval is set to. This way we don't have to have it set to "2 hours" or have another variable defined to have that setting. It can just simply be 1/12th of the interval and it would stink and expand depending on what the overall interval is set to.

**Comment by schalkneethling** [comment]
> @schalkneethling @FrancescoSTL is it technically possible to do 1/12 of the interval for the final sticker offer notification regardless of what the normal interval is set to. This way we don't have to have it set to "2 hours" or have another variable defined to have that setting. It can just simply be 1/12th of the interval and it would stink and expand depending on what the overall interval is set to.

I am sure this is entirely possible.
