### ISSUE TITLE
Sidebar - Utility 3 - Free to Play

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#16]
Sidebar 3 for utility track

## Flow
User clicks on add-on icon
Side bar is opened containing content
User receives the relevant token
The user clicks a "Try it Now" button for one of three themes
The selected theme is applied to the user's browser

**Comment by FrancescoSTL** [comment]
After discussing a bit of design with Matt, this sidebar needs to eventually mirror the AMO cards as specified in https://github.com/mozilla/all-aboard/issues/9.

**Comment by schalkneethling** [comment]
Let close these so we can easily see the overall progress towards v0.5.0
