### ISSUE TITLE
Display "Here's your badge" above badges when CTA is clicked (or sidebar opened on mobile sidebar)

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#166]
On the values track, when the question is answered. On the utility track, when the CTA is clicked except for the mobile 5th sidebar that shows the badge immediately. 

This was coded for issue #143 for values, but it needs to be across both tracks. Issue #143 can just be about the follow up copy based on the answers just for the values track.

Code for the token received was put in #143 but can be associated with this issue now:

https://github.com/schalkneethling/all-aboard/commit/0853a1380e7f74d6bad62226efad06ec9b402778

**Comment by FrancescoSTL** [comment]
Fixed in #196
