### ISSUE TITLE
Convert onboarding add-on into webextensions and a system add-on

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#169]
We need to do more research on if all system add-ons are webextensions or not. Regardless, if this onboarding add-on is successful, it will need to be baked into Firefox and thus it will need to be a system add-on. Also, webextensions are the future of add-ons and we need to ensure we are not building this much longer using the legacy SDK.

**Comment by schalkneethling** [comment]
I reckon it would be best to do this work in a dedicated branch so we do not touch master for anything other than bug fixes. To that end, I created the following branch that is an exact match of master at this time:

https://github.com/mozilla/all-aboard/tree/all-aboard-webextension

@chrismore @FrancescoSTL Thoughts?

**Comment by FrancescoSTL** [comment]
@schalkneethling +1 I think that would be wise as well. We don't want to mess up our v1.

**Comment by schalkneethling** [comment]
I have started work on this and will open a PR against the new dedicated branch. Once we have this merged we should aim for feature parity with the current SDK based add-on. This should be the tracker and we open separate issues referencing this one. Thoughts @FrancescoSTL

**Comment by FrancescoSTL** [comment]
@schalkneethling I think this makes the most sense. We should use this thread for tracking and general high-level strategy discussion related to the conversion.

**Comment by FrancescoSTL** [comment]
Per our team discussion and reflection on the Q3 sprint, I am thinking it would be beneficial to merge an MVP web-extension which can be evaluated for QA iteratively. This will allow the rest of the team to begin finding/filing bugs earlier in the process than they were able to last sprint.

After an MVP is developed, we can implement additional features to bring the web-extension up to speed with the current deprecated add on. I am thinking that a skeleton web extension will do for now, as it sounds like that is what you're working on currently. Thoughts? @schalkneethling

**Comment by schalkneethling** [comment]
That make sense to me. And yes, that is essentially what I am working on ATM.
