### ISSUE TITLE
Build interstitial sticker form iframe page

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#178]
What does everyone think about having the sidebar iframe for the sticker to be a Mozilla-hosted page like www.mozilla.org/firefox/onboarding-reward/. Then when we want the launch the reward we can 301 redirect the www.mozilla.org page to ThinkSmart's servers and we don't have to touch the add-on iframe URL. Then when we want to pull down the form, we just remove the 301 redirect on www.mozilla.org and display an "offer closed".

Another benefit: We don't have to be blocked on the URL from ThinkSmart and if there was any problem with ThinkSmart, we don't have thousands of users out in the world with an add-on with a ThinkSmart hard coded URL. We could simply just pull down the 301 redirect on www.mozilla.org.

**Comment by schalkneethling** [comment]
@chrismore That can work. Perhaps just fly this by Jen Bertsch and pmac so they are aware. So, that will be a full blown page, I take it, not just a 320px by ...

Does that still need to be designed or, are we going to use an existing style like https://www.mozilla.org/en-US/about/ or https://www.mozilla.org/en-US/teach/smarton/

**Comment by chrismore** [comment]
@schalkneethling there is no design needed for the www.mozilla.org page since it will just be embedded in the sidebar. It will be the most basic HTML page with no header/footer and a white background.

**Comment by schalkneethling** [comment]
![screen shot 2016-06-27 at 16 19 38](https://cloud.githubusercontent.com/assets/10350960/16388903/aa63e16e-3c9b-11e6-8b01-d44056215e08.png)

So the page on mozorg will host the form i.e. from the first name input field up to and including the button but, the copy above the first input field and the small print will still live in the sidebar. Correct?

**Comment by FrancescoSTL** [comment]
@chrismore can you add a milestone onto this?

**Comment by chrismore** [comment]
@FrancescoSTL done

**Comment by schalkneethling** [comment]
Seeing I have bedrock already up and running locally, I will take this one. Will have a quick chat with Alex in the morning and get this onto mozorg.

**Comment by FrancescoSTL** [comment]
Thanks @schalkneethling!

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL Talked to Lonnen and Jen Bertsch and they recommended going with heroku. Lonnen can set it up after we have a heroku project created and a stand-alone repo for these remote files.

So first, I created this report to host these static remote files: 

https://github.com/mozilla/all-aboard-remote

For the hostname of this heroku project. We can do firefox-onboarding.herokuapp.com

**Comment by chrismore** [comment]
Jen had a good point about www.mozilla.org. They have tried hard to de-clutter the site of pages that aren't part of bedrock and this onboarding experience isn't really part of www.mozilla.org. So, hosting it somewhere else is better and heroku is a better fit. For a max of 100k users hitting this URL over a few months, there's enough 9's on heroku to handle it. Plus, then it is easier to just push changes to the all-aboard-remote repo and it will automatically propagate to heroku.

**Comment by schalkneethling** [comment]
@chrismore Sounds good to me. I was thinking we might not want things like this living in bedrock anymore. There has indeed been a lot of cleanup happening so, I second going with Heroku here.

**Comment by chrismore** [comment]
Yeah, we don't want to make bedrock messy again :) +1 Heroku

**Comment by chrismore** [comment]
@schalkneethling ping lonnen on IRC for everything. I've already got him up to speed and can respond quickly to helping us get the app ready.

**Comment by schalkneethling** [comment]
Pull request for the above: https://github.com/mozilla/all-aboard-remote/pull/2

**Comment by FrancescoSTL** [comment]
@schalkneethling merged the above

**Comment by FrancescoSTL** [comment]
I believe we need to make a heroku app and then ping Lonnen about adding SSL. He added me to the Mozilla account, so I can make the app if needed @schalkneethling

**Comment by schalkneethling** [comment]
pull request that switches to iframe - https://github.com/mozilla/all-aboard/pull/200

**Comment by FrancescoSTL** [comment]
Fixed in #200
