### ISSUE TITLE
Sidebar - Utility 5 - Free to Roam

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#18]
Sidebar 5 for utility track

## Flow

User clicks on add-on icon
Side bar is opened containing content
User receives the relevant token
User clicks the "Get Firefox on your phone" for either Android or iOS
The user should be shown either the app store or playstore link in a new tab as specified in https://github.com/mozilla/all-aboard/issues/12#issuecomment-223608949

**Comment by schalkneethling** [comment]
Let close these so we can easily see the overall progress towards v0.5.0
