### ISSUE TITLE
Build about:newtab User Data Page

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#189]
Per conversation in #90, we'd like to change show the user that we've auto imported their data by sending them to the new-tab page rather than prompting with a sidebar. This will be executed by appending the previous sidebar copy to the top of the new-tab page with pageMod, and adding an "undo import" link+copy at the bottom of the page.

Additionally, this logic will need to be destroyed after either the first visit, n number of visits, or n time.

**Comment by chrismore** [comment]
Mockup of the modified about:newtab

![newtab-import](https://cloud.githubusercontent.com/assets/751491/16427750/9eadfd40-3d23-11e6-8d58-3bdf1fad1acc.png)

**Comment by chrismore** [comment]
Logic:

```
if (div.newtab-cell:nth-child(1) > div:nth-child(1) > a:nth-child(2) .title does NOT contains "Get Firefox for Android")
{
// Modify first run

    If exists(services.sync.account) {
        // Hide undo sentence at bottom
    }

} else {
// Don't modify first run

}
```

**Comment by chrismore** [comment]
Actually, ignore the first condition, it looks like it is possible for the default tiles to display above history in some cases.

**Comment by chrismore** [comment]
@FrancescoSTL the undo functionality has landed, it won't be functional on our test builds, but we need to figure out how to call it from the undo link at the bottom of about:newtab.

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1271799

**Comment by FrancescoSTL** [comment]
Thanks, @chrismore, I'll implement that in the current PR.

**Comment by FrancescoSTL** [comment]
Merged in #192!

**Comment by chrismore** [comment]
@FrancescoSTL In this sentence:

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/about-newtab-footer.html#L2

Change preferences to data.

Should read:

Didn't want your browser data imported? You can quickly ....

**Comment by FrancescoSTL** [comment]
Can close when #206 merges
