### ISSUE TITLE
Edit "Explore other themes" link below buttons on content 3 on utility track

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#191]
Since we are teasing users with themes, we want to make sure they have a variety to pick from. Let's add a link to https://addons.mozilla.org/en-US/firefox/themes/ that allows them to explore further.

Mockups to follow.

**Comment by FrancescoSTL** [comment]
Is this different from #164?

<img width="1286" alt="screen shot 2016-06-28 at 3 54 49 pm" src="https://cloud.githubusercontent.com/assets/9794516/16435135/a93036d2-3d48-11e6-955b-27fc4919fd25.png">

**Comment by fabiorios** [comment]
Per slack chat today, this is looking too busy. Let's cut out one of the themes. We may need to move the "reset..." and "explore...." up a bit after we remove it.

**Comment by FrancescoSTL** [comment]
@chrismore can you add a priority and milestone to this one?

**Comment by chrismore** [comment]
done with tagging

**Comment by bniolet1** [comment]
We need to tag this url with the correct utm parameters. 

Per: https://github.com/mozilla/all-aboard/issues/147

**Comment by bniolet1** [comment]
So the final link should be: 

https://addons.mozilla.org/firefox/themes/?utm_source=fxonboarding&utm_medium=referral&utm_campaign=onboardingv1

**Comment by chrismore** [comment]
@bniolet1 that's the wrong medium. we need it to be firefox-browser. Anything coming from within firefox needs firefox-browser.

Full correct link for the explore add-ons:

https://addons.mozilla.org/firefox/themes/?utm_source=fxonboarding&utm_medium=firefox-browser&utm_campaign=onboardingv1

**Comment by FrancescoSTL** [comment]
Fixed in #217
