### ISSUE TITLE
Reduce theme buttons on content 3 on the utility track

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#195]
The sidebar is too tall and vertically scrolls.

![screen shot 2016-06-28 at 9 12 19 pm](https://cloud.githubusercontent.com/assets/751491/16440311/9eff270e-3d75-11e6-9bd0-77d172ea9ed5.png)

The easiest thing to do is just remove a theme button.

Remove snow fox.

**Comment by FrancescoSTL** [comment]
Done in #205
