### ISSUE TITLE
Remove import data sidebar, and related assets

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#202]
It is now a done deal that we are going with auto import so, we need to remove everything related to the import data sidebar, clean up the code and hookup the auto import sidebar.

**Comment by FrancescoSTL** [comment]
Probably need to do this as a P1 being that it we have to remove manual import sidebar for user testing.

**Comment by FrancescoSTL** [comment]
Hey @schalkneethling, I'm going to grab this as a part of #204, as I'll need to update the redirection logic anyway for "No Thanks" folks.

**Comment by FrancescoSTL** [comment]
Can close when #206 merges
