### ISSUE TITLE
Update Mozilla newsletter link

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#208]
Three places:

1)

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content5-snippet.html

old URL:

https://www.mozilla.org/?utm_source=fxonboarding&amp;utm_medium=snippet&amp;utm_campaign=onboardingv1&amp;utm_content=community#newsletter-subscribe

New URL:

https://www.mozilla.org/newsletter/mozilla/?utm_source=fxonboarding&amp;utm_medium=snippet&amp;utm_campaign=onboardingv1&amp;utm_content=community

2)

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/values/content5.html

Old URL:

https://www.mozilla.org/?utm_source=fxonboarding&amp;utm_medium=firefox-browser&amp;utm_campaign=onboardingv1&amp;utm_content=community#newsletter-subscribe

New url:

https://www.mozilla.org/newsletter/mozilla/?utm_source=fxonboarding&amp;utm_medium=firefox-browser&amp;utm_campaign=onboardingv1&amp;utm_content=community

3)

https://github.com/mozilla/all-aboard/blob/master/index.js#L335

**Comment by chrismore** [comment]
Currently blocked by this task:

https://tree.taiga.io/project/malexis-mozillaorg-durable-team/us/165

**Comment by chrismore** [comment]
I've updated the newsletter links. We'll keep this open until the page is live.

**Comment by chrismore** [comment]
I checked with Eric to see if page will be published today.

**Comment by JennyDouglas** [comment]
This page is now live: https://www.mozilla.org/en-US/newsletter/mozilla/
