### ISSUE TITLE
Fix CircleCI integration

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#210]
Current CircleCI is hooked up and does build the XPI but, it does not push the resulting XPI anywhere. We need to complete the circle and have it pushed to a deploy branch or to AWS

**Comment by chrismore** [comment]
@schalkneethling is this needed for v1.0 or can we move this to a v2.0 milestone?

**Comment by schalkneethling** [comment]
This is completed as I moved things to TravisCI and unit tests are automatically run now.
