### ISSUE TITLE
Update about:newtab copy with history and bookmark functions

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#211]
Need to update the copy on the page saying their history and bookmarks are imported and link those words to opening the bookmarks menu and history to the awesome bar.

**Comment by FrancescoSTL** [comment]
Copy/ text size under review, but PR is submitted in #212

**Comment by chrismore** [comment]
New copy:

@FrancescoSTL 

All your stuff is ready!
Your favorite [bookmarks] and [website history] are already in Firefox. Boom.

**Comment by chrismore** [comment]
New footer copy too:

"Didn’t want your bookmarks and history imported? You can quickly [undo the import]."

**Comment by FrancescoSTL** [comment]
@chrismore done in #212

**Comment by FrancescoSTL** [comment]
Merged
