### ISSUE TITLE
Include sticker URL for iframe on reward side panel

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#224]
Here is the URL they plan on using.

https://mozilla.thinksmart.com/

**Comment by chrismore** [comment]
This will go as a on the all-aboard-remote repo as redirect.

**Comment by fabiorios** [comment]
Looks like it's live. I'm told they are still working on it, but the page exists now.

**Comment by chrismore** [comment]
This should be a 301 redirect from the heroku index to https://mozilla.thinksmart.com/

**Comment by fabiorios** [comment]
Thinksmart says the form will be resized by EOD today. We should get this into the next funnelcake

**Comment by schalkneethling** [comment]
This is complete, no changes required to add-on

**Comment by fabiorios** [comment]
Form updated and ready!
