### ISSUE TITLE
Clicking light bulb notification when sidebar is open before first notification closes sidebar

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#225]
1) first run 
2) answer questions
3) no thanks fxa
4) before you get the desktop notification click the light bulb icon 5
5) sidebar open 

Actual results:

get notification and click the light bulb, sidebar closes.

Expected results:

It kept the sidebar open and didn't close it.

**Comment by FrancescoSTL** [comment]
@schalkneethling noted feedback in #251

**Comment by FrancescoSTL** [comment]
Fixed in #251
