### ISSUE TITLE
Not engaging with first content notification destroys the addon upon closing Firefox

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#226]
1. Create a fresh Firefox profile
2. Launch browser and go to about:config
3. change "xpiinstall.signature.required" setting to "false"
4. install add-on xpi from file. 
5. visit first run page
6. answer questions 1 and 2
7. no thanks on account. 
8. wait for the desktop notification 
9. do not open the sidebar, click the lightbulb nor the desktop notification. 
10. close Firefox
11. re-launch Firefox
12. The lightbulb in the Chrome is gone and the add-on will not do anything even though the add-on is still present on the add-ons menu.

**Comment by bniolet1** [comment]
The add-on lightbulb disappears on restart even if you "x" out of the desktop notification. 

When you re-start the browser, there is no more lightbulb and no more content interaction, even though "all-aboard" is still listed as an add-on in your add-ons manager.

**Comment by bniolet1** [comment]
Here is my config.json: 

{
    "afterInteractionCloseTime": 5000,
    "defaultSidebarInterval": 10,
    "defaultSidebarCloseTime": 7000,
    "timeElapsedFormula": 1000,
    "waitInterval": 10000
}

**Comment by chrismore** [comment]
@schalkneethling need to get this resolved on Monday 2016-07-04.
