### ISSUE TITLE
Clicking through badges loads a sidebar 

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#227]
I'm currently in the privacy content (#4 of the values track)

If I click the Firefox badge it loads this URL in the address bar: resource://all-aboard/data/tmpl/values/content3.html

**Comment by fabiorios** [comment]
![doubles](https://cloud.githubusercontent.com/assets/19597198/16535173/49dde8ce-3f9a-11e6-9b7d-d19ca261c577.JPG)

**Comment by chrismore** [comment]
@schalkneethling I am able to replicate this now and we found the pattern.

1) Answer at least through content 3 sidebar or all.

2) Ensure content 3 is answered

3) Click the heart

4) Click the Firefox icon

BOOM.

content 3 opens in the main window.

Very weird. Only pattern we can find to make this happen. Is this a @schalkneethling easter egg??

**Comment by chrismore** [comment]
@schalkneethling another thing that could be related to it is when the heart icon is clicked, you can't click the sun icon.

**Comment by chrismore** [comment]
@schalkneethling need to get this resolved on Monday 2016-07-04.
