### ISSUE TITLE
Make Iframe Dynamic

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#232]
We need to resize the iframe based upon its content size so that, in the event that we need to change iframe content (ex: thinksmart sends us their iframe and the dimensions are different then what we have accounted for) it will change without needing to change the addon.

That, or we simply ask the thinksmart people how big their iframe content will be and resize ours explicitly to match.

**Comment by chrismore** [comment]
@schalkneethling need to get this resolved on Monday 2016-07-04.

**Comment by schalkneethling** [comment]
Currently the `iframe` element itself contains no with or height setting inline, and all that the CSS is doing is turning of borders and setting the width to 100% of our available width. With all of the work that was done to ensure as much of the content is "above the fold" so to speak, I would suggest we define the height (220px) and ensure that ThinkSmart stays within those parameters.

**Comment by chrismore** [comment]
@schalkneethling may need to increase the iframe height or see if we can make the height dynamic to the contents of the child frame.

I know that the iframe on /firstrun/ on bedrock is dynamic to the size of the child iframe, but I am not sure exactly how they are doing it.

**Comment by chrismore** [comment]
Asking ThinkSmart if they can deal with a 220px height with any error messages.
