### ISSUE TITLE
Delay any desktop notification for 60 seconds after browser opens

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#233]
Per the original flow, we wanted to wait 60 seconds any time the browser is opened before displaying a notification. So, if it has been exactly 24 hours after the first sidebar is opened and Firefox is opened, the notification should happen at 24 hours and 60 seconds. This will prevent the user from being pinged immediately when they open the product when they probably had a task in mind.

**Comment by FrancescoSTL** [comment]
Fixed in #240
