### ISSUE TITLE
First Run Not Modified when any parameters exist after /firstrun/

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#234]
The first run page is modified when it doesn't have any parameters on the trailing slash like:

https://www.mozilla.org/en-US/firefox/47.0/firstrun/

But funnelcakes always have parameters after the / like:

https://www.mozilla.org/en-US/firefox/47.0/firstrun/?f=85
https://www.mozilla.org/en-US/firefox/47.0/firstrun/?f=86

This is a simple regex change:

https://github.com/mozilla/all-aboard/blob/master/index.js#L89

old:

`var firstrunRegex = /.*firefox[\/\d*|\w*\.*]*\/firstrun\//;`

new, just adding .* after the trailing slash:

`var firstrunRegex = /.*firefox[\/\d*|\w*\.*]*\/firstrun\/.*/;`

**Comment by FrancescoSTL** [comment]
Merged
