### ISSUE TITLE
Nightly funnelcake build presents two copies of the first run questions flow

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#243]
When running a clean install of this funelcake build with a new profile, the first run experience presents two separate copies of the first run experience. 

http://archive.mozilla.org/pub/firefox/candidates/47.0.1-candidates/build1/funnelcake86/win32/en-US/firefox-47.0.2.en-US.win32.installer.exe

Both appear to function and both are present as you interact with the two questions. The doubling disappears after you click the "Go" button (answer both questions then get to the accounts page). 

steps to reproduce:
uninstall all versions of Firefox
install nightly
run profile manager (firefox.exe -p)
delete profile
create new profile
start nightly

![image](https://cloud.githubusercontent.com/assets/14222130/16588309/7f96e52e-429c-11e6-9fe5-cc4e4a60ea44.png)

![image](https://cloud.githubusercontent.com/assets/14222130/16588316/84393064-429c-11e6-9ec4-d978a21cf669.png)

**Comment by chrismore** [comment]
![pasted_image_at_2016_07_05_10_57_am](https://cloud.githubusercontent.com/assets/751491/16591689/dd6ccebc-4291-11e6-8fa3-0c0991868983.png)
Happening on about:newtab too

**Comment by chrismore** [comment]
I inspected the html on both pages and it is inserting the section html multiple times.

**Comment by chrismore** [comment]
It looks like @FrancescoSTL has a check for newtab to not modify it more than once, but not sure why that isn't working. https://github.com/mozilla/all-aboard/blob/master/index.js#L1020

**Comment by schalkneethling** [comment]
> It looks like @FrancescoSTL has a check for newtab to not modify it more than once, but not sure why that isn't working. https://github.com/mozilla/all-aboard/blob/master/index.js#L1020

This is why I am wondering whether something is fishy with `simpleStorage` in the build :-/
On that note, @chrismore, where can I get a funnelcake build?

**Comment by chrismore** [comment]
installer http://archive.mozilla.org/pub/firefox/candidates/47.0.1-candidates/build1/funnelcake86/win32/en-US/firefox-47.0.2.en-US.win32.installer.exe

**Comment by FrancescoSTL** [comment]
Fixed in #245
