### ISSUE TITLE
New sidebar is available even without notification

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#244]
I'm using the funnelcake and closing and reopening Firefox and then clicking on the bulb presents new sidebar without delay. I don't have to wait for a notification.

**Comment by schalkneethling** [comment]
This is most likely related to https://github.com/mozilla/all-aboard/issues/243

**Comment by schalkneethling** [comment]
@FrancescoSTL @chrismore can we confirm that this is now also resolved?

**Comment by chrismore** [comment]
@FrancescoSTL did you test to see if #243 resolves this?

**Comment by FrancescoSTL** [comment]
This wasn't addressed in #243. I think it came about with a previous PR, not sure which one.

**Comment by FrancescoSTL** [comment]
Actually, if IIRC, there was an issue with showing the notification and the badge at the same time, as some error was being thrown. @schalkneethling noted this somewhere previously. I'll attempt to find the comment

**Comment by FrancescoSTL** [comment]
Either way, is this an issue? @chrismore I think we discussed previously that it would be fine to show the badge to users before the first notification, because if they are interested, there wasn't an issue with them starting the flow early.

**Comment by FrancescoSTL** [comment]
Ah wait, I may have misunderstood the issue. I was unaware of this. Let me see if I can replicate

**Comment by FrancescoSTL** [comment]
Seems to be fixed, as I can't replicate it. I'll close and we can reopen if we see it in the future.
