### ISSUE TITLE
Distribution.id is not being set/updated when clicking "no thanks" on first run quesitons

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#255]
Distribution.id initial variations QA

* new + do good: mozilla86-values-new

* new + do it yourself: mozilla86-utility-new

* existing + do good: mozilla86-values-existing

* existing + do it yourself: mozilla86-utility-existing

* no thanks: no value (the issue itself)

When clicking no thanks, the value should be mozilla86-no-thanks.

**Comment by schalkneethling** [comment]
> When clicking no thanks, the value should be mozilla86-no-thanks.

@chrismore Oh wow, I must have missed this entirely.

**Comment by FrancescoSTL** [comment]
Fixed in #252
