### ISSUE TITLE
Funnelcake - snippets not loading, shows "null"

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#256]
After installing Firefox and closing it once, if I open it the about:home page loads and there is not snippet. Instead, on the right side of the searchbar within the page, there's text that says "null".

This occurs regardless of the track and opt-in/opt-out of accounts. Also, even if I don't close Firefox and simply go to about:home and refresh, no luck.

![null](https://cloud.githubusercontent.com/assets/19597198/16628961/b91fa6ec-4368-11e6-962a-4dfdad8fe5aa.JPG)

**Comment by FrancescoSTL** [comment]
@fabiorios fixed in #248

**Comment by FrancescoSTL** [comment]
Thanks, though. This wasn't noted as an issue, so it would've been hard for you to know that it was already fixed 😀. Keep breaking things @fabiorios
