### ISSUE TITLE
Funnelcake - Private browsing button on utility content #2 not working

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#257]
Loading the sidebar is fine, but when I click on the try it button, I get a stamp, but the door hanger and highlighting of the PB doesn't happen.

(fyi - I tried this on the values track and the PB text link works fine)

New user
Do it yourself
No thanks to accounts
click the bulb notification
load content 1 and try search to get a badge
close firefox
open firefox and load sidebar content 2
click the try it button

**Comment by fabiorios** [comment]
If I close and reopen Firefox, the button doesn't work
If I don't close and reopen Firefox, it works fine.
If it works fine, and then I close and reopen Firefox, and go back to the PB sidebar, it doesn't work.

**Comment by chrismore** [comment]
I've tried this locally and on a Windows 10 machine and it has worked fine.

**Comment by chrismore** [comment]
Tested on multiple machines and this appears to work fine.
