### ISSUE TITLE
Funnelcake - First run experience can be repeated even after completing it

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#258]
Steps to reproduce (no existing profile, fresh install): 

1. Complete onboarding questions
2. Hit “No thanks” on accounts page, which should navigate you away from that page
3. Leave both tabs open
4. Open about:preferences and delete cache
5. Navigate back to http://mozilla.org/en-us/firefox/46.0/firstrun on an already open tab

Expected result: Firefox accounts page shown. 

Actual result: First run questions appear again. 

6. From here, repeat process (answer both questions)
7. hit "not thanks" on accounts. 
8. navigate back to first run page. 

Firefox accounts page correctly shown.

**Comment by FrancescoSTL** [comment]
@bniolet1 if you close Firefox and then reopen after going through onboarding, does it show you the golden question again? If not, this bug is not a huge priority I suppose.

**Comment by bniolet1** [comment]
I can't confirm this because if I answer the questions and close Firefox (whether or not I have engaged with content) lightbulb is gone when I reopen Firefox. 

See issue #254

**Comment by schalkneethling** [comment]
TEST 1
----------
Machine: Mac OSX
Browser: Firefox 47

1. Installed XPI built of master
2. Load /firstrun page
3. Answer questions
4. Click No thanks on FxA
5. Sent to about:newtab which shows the "migration already happened header"
6. Received first notification, engaged
7. Completed the entire process up to the sticker reward.
8. Went to about:preferences and hunted around for clear history, cleared cache
9. Force reloaded /firstrun
10. No question, only FxA form visible.

**Comment by schalkneethling** [comment]
TEST 2
----------
Machine: Max OSX
Browser: Firefox 49.0a2 (dev edition)

1. Installed XPI built of master
2. Load /firstrun page
3. Answer questions
4. Click No thanks on FxA
5. Left both tabs open
6. Went to about:preferences and deleted cache
7. Navigated back to http://mozilla.org/en-us/firefox/46.0/firstrun on an already open tab
8. No question, only FxA form visible.
9. Notification still active with badge
10. Clicking notification shows first step

**Comment by FrancescoSTL** [comment]
Potential fix is merged and awaits testing with the next funnelcake build.

**Comment by fabiorios** [comment]
@FrancescoSTL this is no longer an issue for me on v7. Navigating back simply displays the accounts form.
