### ISSUE TITLE
Funnelcake(v5) - Undo import text is left aligned and unstyled

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#262]
Steps to reproduce: 

No Firefox profile present. 
Default browser = Chrome. Chrome is closed during installation / first run. 
Install v5 of the funnelcake build: 

https://archive.mozilla.org/pub/firefox/candidates/47.0.1-candidates/build1/funnelcake86-testing/v5/win32/en-US/firefox-47.0.1.en-US.win32.installer.exe

Answer two questions, "no thanks" past Accounts page. 

Migration tool fires, but the undo text is left aligned and apparently unstyled (probably the same CSS issue). 

![pasted image at 2016_07_07 10_55 am](https://cloud.githubusercontent.com/assets/14222130/16657868/0914b664-4432-11e6-9517-8077c6f5636e.png)

@FrancescoSTL Tagging you in.

**Comment by bniolet1** [comment]
FYI: this bug also occurs in v4 of the funnelcake build. 

Same steps to reproduce, except install this .exe: 
https://archive.mozilla.org/pub/firefox/candidates/47.0.1-candidates/build1/funnelcake86-testing/v4/win32/en-US/firefox-47.0.1.en-US.win32.installer.exe

**Comment by FrancescoSTL** [comment]
Need to change auto import footer class to allaboard-auto-import.

Thanks @bniolet1!

**Comment by FrancescoSTL** [comment]
Fixed in #264
