### ISSUE TITLE
Clicking light bulb on 2nd notification when sidebar is open doesn't do anything

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#263]
Steps to reproduce:

* jpm latest master
* answer yup or nope
* answer do good or do it yourself
* click no thanks on fxa
* new tab opens
* wait for first notification
* click it
* sidebar opens with content 1
* leave sidebar open
* wait for 2nd notification
* click either light bulb or notification

Expected results:

* sidebar refreshes with content 2

Actual results:

* sidebar 1 content says and you don't see content 2. You have to close and re-open sidebar to see content 2.

This appears to only happen on the 2nd notification on either track.

I believe this is a regression due to issue #225 and that for some reason the changes in #225 think that the sidebar being open on the 2nd time is the first. If I have the sidebar open the first time that issue #225 resolves, the issue described above doesn't happen.

**Comment by chrismore** [comment]
@schalkneethling ^^

**Comment by schalkneethling** [comment]
I am leaning towards marking this a wontfix. Here is my reasoning. With the actual delay between notifications, the only way you can run into this is if you open the first sidebar, and then never interact with the icon again until the next notification, and still have the first sidebar open.

This will be impossible as the sidebar will auto-close after 5 minutes of no interaction (so you will have to click the icon again to show it) or, will close in 2 minutes if you interact (again, you will have to click the icon again to show it).

If there is no sidebar visible, then this code[https://github.com/mozilla/all-aboard/blob/master/index.js#L675] will not execute. Thoughts @chrismore ?

**Comment by chrismore** [comment]
Going to move this to v2. This would only happen in the last 2 minutes before the 24 hour interval timer. You would have to open it up <1:59 minutes before the next notification and have it open. If it was 2:01 before, it would auto close it with 1 second to go and then the notification would trigger and clicking would re open it.

**Comment by schalkneethling** [comment]
@chrismore This is resolved correct?

**Comment by chrismore** [comment]
yup
