### ISSUE TITLE
Create timers object

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#265]
This is simply a cleanup/improvement. It would be nicer to have an object called `durations` that holds all of our various timing variables. Easier to parse mentally and keep organized. So, instead of having just `defaultSidebarCloseTime` defined somewhere at the top, it would live inside the `durations` object so, you would do:

```
durations.defaultSidebarCloseTime
```
Small thing, but makes the code more readable and maintainable I reckon.

**Comment by FrancescoSTL** [comment]
Something else we should consider is how to deal with timer persistence between sessions. I'm not certain that storage.local will support timers, as it seems to only support objects storing key/value pairs (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Storage/StorageArea/set). If we'd like to file this as a separate issue, I'm fine with that as well @schalkneethling

**Comment by schalkneethling** [comment]
This done as part of PR https://github.com/mozilla/all-aboard/pull/325
