### ISSUE TITLE
Funnelcake(v5) - snippet content doesn't align with side panel content

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#266]
Current result: If I see the PB sidebar and get the PB badge, the next time I load Firefox I'll get PB snippets. 
Expected result: The PB sidebar and snippets should run along the same timeline.

I've replicated on W7 and W8. @bniolet can you review on W10

**Comment by bniolet1** [comment]
I'm not seeing this on W10. 

I have to manually refresh on about:home (because you can't close the browser without killing the add-on in the current build), but snippets are aligned correctly for both flows for me.

**Comment by fabiorios** [comment]
OK, might be good to hold until we can properly test this one. I'm able to refresh and see the correct snippet, but not before I engage with the sidebar. 

In other words, if the notification is ready, and I haven't clicked it, I'll continue to see yesterday's snippets. Even if I refresh about:home.

Once I click the notification and see the PB sidebar, I can refresh about:home and see PB snippets.

**Comment by FrancescoSTL** [comment]
Likely fixed by #298
