### ISSUE TITLE
Sticker iframe not tall enough to fit form and handle error messages.

### ISSUE THREAD

**Issue by AbeMasresha** [mozilla/all-aboard#268]
Steps to Reproduce:

1.	Select “yup” for the first question "Have you used Firefox in the last 30 days?”
2.	Select "Do good" for the second question
3.	Click “Go”
4.	Click “No thanks” below the Create account form
5.	Click the notification or the addon
6.	Select your answers and click “Show Answer” for all the five questions
7.	Click “Claim your prize!”
8.	Do not fill the form and click “Send me a sticker!”

Expected Result: 
Error message should be clearly displayed to the user. 

Actual Result:
Error message is partially displayed.  Only part of the message is displayed.
Here is the screen capture:  https://testing-1.tinytake.com/sf/ODA2MTg4XzM1ODU5NjU

Environment:
Version 	47.0.1
Build ID 	20160705164658
Update Channel 	release-cck-mozilla86
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by chrismore** [comment]
Thanks @AbeMasresha ! Let's check in with @fabiorios to see the status of the sticker form. It is currently hosted and managed by a 3rd party website.

**Comment by fabiorios** [comment]
@chrismore having them edit these. Thank you.

**Comment by chrismore** [comment]
https://github.com/mozilla/all-aboard/blob/master/data/css/all-aboard.css#L236

@FrancescoSTL change to 240px height.

**Comment by FrancescoSTL** [comment]
Done. Now blocked by iframe vendor folks. I'll mark this as a blocked tracking issue.

**Comment by chrismore** [comment]
I have also reduced the padding on the sidebar for the sticker, which will give the form more room. We have also asked the 3rd party vendor to make these changes to their form.

https://mozilla.thinksmart.com

1) Align the form to the top left of the page. Currently, it is vertically centered and that doesn't work for our application well.

2) The longest error message isn't able to be displayed fully on the screen. If you leave all of the form fields empty, it doesn't fit. See screenshot below.

**Comment by chrismore** [comment]
This will not block release since the form is hosted externally and outside the add-on.

**Comment by schalkneethling** [comment]
close for v1 launch? @chrismore
