### ISSUE TITLE
Qutting Firefox with sidebar open loses tokens

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#271]
Steps to re-produce:

1) answer questions

2) receive a token from clicking a CTA

3) quit Firefox

4) re-opening Firefox

Expected results

Sidebar should be closed and my tokens should be still inside of it.

Actual results

All badges are done, but onboarding is still at the same step. 

You can fix it inside the experience by:

1) Closing sidebar

2) Quit Firefox

3) Open Firefox

There is some issue caused by quitting Firefox with the sidebar open that it messes up this and other experiences.

**Comment by FrancescoSTL** [comment]
This seems to be tied to the method of exiting Firefox using command+q in OSx. It doesn't happen if you exit from the UI and then quit Firefox from your menu-bar. Additionally, I tested this in Windows which I was unable to replicate through normal closing of Firefox, and also through hitting alt+f4. Until we can replicate with an xpi in Windows or through closing Firefox normally in OSx, I think we would be safe in closing this. The above also seems to be causing #274 when testing.
