### ISSUE TITLE
Notification is triggered 60 seconds after open up Firefox after the prize sidebar is viewed for all future sessions

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#272]
Steps to re-produce:

1) Answer questions

2) Engage with all CTAs

3) View prize sidebar

4) Quit Firefox

5) Open Firefox

6) Wait 60 seconds

Expected results:

Nothing

Actual results:

Receive notifications about prize sidebar

**Comment by FrancescoSTL** [comment]
Fixed in #279
