### ISSUE TITLE
Qutting Firefox with sidebar open, keeps sidebar open on next session

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#274]
Steps to re-produce:

1) Answer questions

2) Open any sidebar leave sidebar open sidebar

3) quit Firefox

4) open Firefox

Expected results:

No sidebar open

Actual results:

sidebar is still open.

I believe this is also related to issue #271

**Comment by FrancescoSTL** [comment]
This seems to be tied to the method of exiting Firefox using command+q in OSx. It doesn't happen if you exit from the UI and then quit Firefox from your menu-bar. Additionally, I tested this in Windows which I was unable to replicate through normal closing of Firefox, and also through hitting alt+f4. Until we can replicate with an xpi in Windows or through closing Firefox normally in OSx, I think we would be safe in closing this. The above also seems to be causing #271 when testing.
