### ISSUE TITLE
Clicking explore other themes on utilities content 3 opens in a new Firefox window

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#276]
If you click the "explore other themes" on content3.html on the utilities track, it open in a completely new Firefox window. This will probably likely due that it needs an intent handler (https://github.com/mozilla/all-aboard/blob/master/index.js#L416) defined for that link.

**Comment by schalkneethling** [comment]
@chrismore There are a couple of other instances where this happens as well. The app badges come to mind. Should I fix all of those as well?
