### ISSUE TITLE
Eliminate scroll bars from the most common resolution

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#283]
The most common resolution of users who experience the add on will be 1366x768.

We have tested it and we are getting scroll bars.

Utility

* free to play (horizontal by ~30px)
* free to roam (horizontal by ~20px)

values

* privacy (horizontal by ~60px)
* security (horizontal by ~60px)
* community (horizontal by ~50px)

Sticker

* sticker (horizontal and vertical)

**Comment by chrismore** [comment]
Here's some options:

Free to play: Remove the 2nd theme button and only have 1

Free to roam: make the mobile buttons much smaller. They are kind of giant now with the size of the sidebar.

Privacy: Reduce follow up to a single line

From:

No other browser gives you so much control. Try Private Browsing.

To:

Try Private Browsing

Security: Reduce follow up to just a few words: 

From:

Improve your security online with these safety measures

To: 

Online security help

* Community: Get it down to one line.

From:

Love the Web? Get the Mozilla newsletter

To:

Get the Mozilla newsletter

**Comment by chrismore** [comment]
We could also cut the padding around the header images in half again and that would save space everywhere.

**Comment by bniolet1** [comment]
All of the text and content changes are just fine with me @chrismore .

**Comment by chrismore** [comment]
and for the sticker, we are going to have to go 20px wider and 30px longer. That means the width is going to have to be set to something more than the 100% that it is now. The form looks to only be responsive down to 340px.

**Comment by chrismore** [comment]
I got the following copy already already:

* Removed  "No other browser gives you so much control." on values content3.html
* Removed  Improve your security online with these and changed link to Get security tips on values content4.html
* Removed "Love the web?" from values content5.html

What's left to do:

* remove Try Cozy Fox button from utility content3.html and array in index.js (fine to keep it as an array for future potential of multiple)
* Make mobile buttons 25% smaller width and height

**Comment by chrismore** [comment]
I've got this whole issue wrapped up.

Remove one theme button and reduced size of the mobile buttons.

I have one PR open https://github.com/mozilla/all-aboard/pull/288

**Comment by chrismore** [comment]
This should all be resolved now.
