### ISSUE TITLE
Snippets will never show up for users -- ever

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#284]
Ok, here's the deal, about:home snippet modifications will not show up for users. 

Why?

Because snippet modifications are only trigger after you have received a notification. The notification updates about:home, but about:home is only loaded when you first open Firefox. The only way for a user to load about:home outside of opening up Firefox, is to click the Firefox home button thus most users will never see snippets.

Solution:

Load and modify about:home snippets exports.main so that it can modify about:home when it first opens. The snippets content number should be whatever content sidebar they are currently on. For first session people, that would be content 1 and so on.

**Comment by chrismore** [comment]
Actually, I got this to work. Hang on a minute for some testing.

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL something to figure out this weekend. I wonder if we will just have to call modifyAboutHome(track, step) in the index main so that it is running all the time when the add-on first loads.

**Comment by chrismore** [comment]
I found a potential solution to this, but it will require other modifications.

If I add the follow functions to line 1160 conditional from:

```
    if (typeof simpleStorage.step === 'undefined'
        && typeof simpleStorage.isOnBoarding !== 'undefined') {
        startNotificationTimer(1);
        addAddOnButton();
    }
```

```
    if (typeof simpleStorage.step === 'undefined'
        && typeof simpleStorage.isOnBoarding !== 'undefined') {
        startNotificationTimer(1);
        addAddOnButton();
	sidebarProps = getSidebarProps();
	modifyAboutHome(sidebarProps.track, sidebarProps.step);
    }
```

It only modifies about:home and displays snippets as soon as Firefox restarts and the isOnboarding is defined. The issue is with the modifyAboutHome function is modifying about:home, but you have to refresh the page instead of live modifying it.

**Comment by FrancescoSTL** [comment]
@chrismore so if I understand this correctly, the issue is not that users will *never* see snippets, but rather, that they won't see snippets until they've opened the sidebar for that step?

**Comment by FrancescoSTL** [comment]
Whoops, didn't mean to hit close

**Comment by chrismore** [comment]
@FrancescoSTL no, they never ever see snippets because a user will only see about:home when Firefox loads at the start of a new browsing session and the snippet page mod only happens after a notification is triggered and since we have a 60 day delay for a notification, they won't see a about:home mod on load of Firefox.

**Comment by chrismore** [comment]
It seems like the about:home page mod only works after a sidebar has been opened. I am testing this on the Windows machine again now.

**Comment by FrancescoSTL** [comment]
@chrismore My brain is in debugging mode. For some reason I stopped equating about:home to the Firefox start page.. Probably because I've been starting it with firstrun for the last two weeks 😅

**Comment by FrancescoSTL** [comment]
I'll have a PR for this in tonight for review!

**Comment by chrismore** [comment]
yeah, start page only loads when Firefox starts thus it doesn't get modified until a sidebar is open and it was fine during testing because we were in one session and refreshing about:home. That scenario wouldn't ever happen in the real world. :)
