### ISSUE TITLE
If you sign up for FxA onboarding will not start until you restart Firefox

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#286]
Steps to reproduce:

1) Answer questions

2) Sign up for FxA (make up something like cmore+45444646665@mozilla.com)

3) Save settings

Expected results

Light bulb icon would have shown up and timer started

Actual results

No light bulb icon until Firefox is restart. If Firefox is kept open forever, onboarding will never start. If it was kept open for a week and then restarted, onboarding wouldn't start for a week. 

Suggestion:

Add light bulb and start timer as soon as you click "Go" on the questions. Users are not going to be staring at the FxA form for 24 hours and then get distracted by the light bulb icon. Yes, during our 10 second tests it may not make sense, but it will never be 10 seconds.

**Comment by chrismore** [comment]
I am close to figuring this one out, but I am stuck. I am trying to do something as follows modifyFirstrun() function:

`
worker.port.on("message", function(e) {
	console.log("fxa before")
	var data;
	data = JSON.parse(e.data);
	if (data.command == "signup_must_verify") {
		console.log('fxa listener after messag=' + message);
		// user has signed up or logged in to FxA
		// Start onboarding
        if(typeof simpleStorage.step === 'undefined') {
            addAddOnButton();
        }
		startNotificationTimer(1);
	}
});
`

What I am having trouble with is if I should we using tabs.port or worker.port.on.

**Comment by FrancescoSTL** [comment]
Seems as though this won't be much of an issue, as we are still starting onboarding for the user anytime they exit the firstrun page or re-load firefox. As such, we'll close for now and reopen if we find there to be a hole in our logic.
