### ISSUE TITLE
Bookmark Highlight Content 4 Snippet Never Dismissed

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#294]
If you highlight the bookmark toolbar using the "Try it Now" button on Utility content 4, it will never be dismissed unless you close firefox and reopen.

**Comment by chrismore** [comment]
https://github.com/mozilla/all-aboard/blob/master/data/tmpl/utility/content4-snippet.html

**Comment by FrancescoSTL** [comment]
Merged
