### ISSUE TITLE
Provide onboarding experience for legacy /whatsnew/ users users

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#297]
Currently, only /firstrun/ users will get onboarding and /firstrun/ only loads when there is no profile on the machine. They are either existing users on a new machine or really new users. We should do something for existing users on machines with existing profiles.

**Comment by FrancescoSTL** [comment]
I am thinking that it is worthy having a discussion about what this experience will look like for /whatsnew/ users. I think that it is likely this cohort of users is not represented by any subset of our current test group.

If we are going to customize the experience for this cohort, we should probably also have the discussion as to whether it is worth segmenting the experience further within our current group, what segment it would be most important to develop for, and how much time each of these branches will take.
