### ISSUE TITLE
Determine Whether E10s Will Break Anything

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#299]
In the case that e10s rolls out to existing users before our add-on self destructs, we should test the funnelcake with e10s enabled and ensure nothing blows up in our faces.

**Comment by schalkneethling** [comment]
I believe we will be ok here when we move to web extensions but, a valid tracker.

**Comment by schalkneethling** [comment]
Nope, this is one of the reason why we should be moving to web extensions:

> The technology is developed for cross-browser compatibility: to a large extent the API is compatible with the extension API supported by Google Chrome and Opera. Extensions written for these browsers will in most cases run in Firefox with just a few changes. The API is also fully compatible with multiprocess Firefox.
