### ISSUE TITLE
First notification will not be triggered unless user completes first CTA

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#303]
There was a problem with the logic in the add-on and it didn't handle triggering the first notification because the timer kept restarting each launch of Firefox. When testing this locally, we never noticed this because we usually keep Firefox open or if we restart, and thus resetting the timer back to the original value (instead of counting down from the previous session's time left).

This was confirmed by various Mozillians waiting for their first notification and the only people that did manually clicked the first CTA or kept Firefox open forever.

**Comment by FrancescoSTL** [comment]
Shipping #304 with users upgrading to v1.1
