### ISSUE TITLE
Rework the flow of the add-on

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#305]
The current implementation of the flow of the add-on is problematic, hard to maintain, and error prone. I propose we step back, define a flow diagram that makes sense, is clearly explained and then implement this as a flow manager in the rewrite we are doing to web extensions.

All flow related logic should live in the `flowManager` to ensure encapsulation, ease of maintenance and unit testing.

**Comment by FrancescoSTL** [comment]
+1,000,000 this. Debugging is a nightmare at the moment and I think we have more conditionals than we can sustain. That, combined with the fact that our backend js is stored within one 1200 line file is really muddying the waters when attempting to debug.

We will definitely need to have some architecture discussions for v2! Thanks @schalkneethling

**Comment by schalkneethling** [comment]
Completed as part of making the app modular.
