### ISSUE TITLE
turn up the gamification

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#315]
Our v1 introduced individual badge rewards and a single reward at the conclusion of onboarding. I'd like to scatter the rewards and also make them unexpected. A predictable reward quickly loses its value, so it's likely our badges become less effective quickly.

Ideas: 
provide a reward on day one. 
offer a tangible reward before the end
provide a reward a specific day of the week
add a puzzle or mini-game
show progress as compared to other users
mix it up and have no CTA sometimes
...

**Comment by schalkneethling** [comment]
This has been done right? @chrismore @fabiorios

**Comment by chrismore** [comment]
we Incorporated most of it
