### ISSUE TITLE
Integrate with FxA/basket metrics pipeline

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#33]
Hi @schalkneethling! Further to the email thread from Ben Niolet, let's coordinate on the interface between this addon and Firefox Accounts.

Over in [1], [2] I've been tweaking the way that Firefox Accounts communicates login events to basket, in order to support the metrics needed for experiments here. The idea is for users bucketed into either the "values" or "utility" group, to end up subscribed to a corresponding newsletter in basket.

End-to-end, I see the flow working as follows:

This addon loads https://accounts.firefox.com in the first-run page iframe, and specifies two important query parameters: utm_campaign set to a known value unique to this experiment, and utm_content set to the name of the corresponding newsletter in basket.

When the user completes login with Firefox Accounts, it queues an event to SQS containing details about the login, including the values of the utm_* query parameters.

A handler listening for these events, reads it off the queue, detects the special value of utm_campaign, and makes a call to basket to subscribe the user to the newsletter named in utm_content.

Does this seem reasonable from your perspective?

If so, I think the next steps are simply to agree on the strings to be used in utm_campaign and utm_content, and then coordinate on deployment and timing of all the moving parts.

[1] mozilla/fxa-basket-proxy#27
[2] mozilla/fxa#148

**Comment by chrismore** [comment]
Iframe code in bedrock:

https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/firstrun/firstrun.html#L74

iframe url with variables:

{{ settings.FXA_IFRAME_SRC }}?utm_campaign=fxa-embedded-form&amp;utm_medium=referral&amp;utm_source=firstrun&amp;utm_content=fx-{{ version }}&amp;entrypoint=firstrun&amp;service=sync&amp;context=iframe&amp;style=chromeless&amp;haltAfterSignIn=true

Example URL:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

A few options:

Note: -moz = mozilla values and -fx = firefox utility flow

A) Append the utm_campaign with -moz or -fx

Example:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form-moz&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form-fx&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

2) Append the utm_content with -moz or -fx

Examples:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0-moz&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0-fx&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

**Comment by chrismore** [comment]
another option:

3) Use the same UTM parameter that exists on the form now, but add an additional one just for this experiment:

&onboarding=moz-values or &onboarding=fx-utility

Example:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true&onboarding=moz-values

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-46.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true&onboarding=fx-utility

**Comment by chrismore** [comment]
@rfk ^^ r?

**Comment by rfk** [comment]
Option (2) seems closest to what I had in mind, if we created corresponding subscriptions in basket named `fx-46.0-moz` and `fx-46.0-fx`.

**Comment by chrismore** [comment]
Talked @rfk and Ben and we are going with option #1, just appending -moz and -fx to the end of the utm_campaign parameter. We'll leave the rest alone.

**Comment by chrismore** [comment]
@schalkneethling ^^ here's the decision for the iframe URL.

Original URL:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=firstrun&utm_content=fx-47.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

Mozilla values track:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form-moz&utm_medium=referral&utm_source=firstrun&utm_content=fx-47.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

Firefox utility track:

https://accounts.firefox.com/?utm_campaign=fxa-embedded-form-fx&utm_medium=referral&utm_source=firstrun&utm_content=fx-47.0&entrypoint=firstrun&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true

**Comment by rfk** [comment]
FYI I'm adding the agreed-on `utm_campaign` values and their corresponding subscriptions here:

  https://github.com/mozilla/fxa-basket-proxy/pull/28/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R56

@chrismore I invite you to do a quick sanity-check that we've got the values as expected.

**Comment by chrismore** [comment]
@rfk looks good to me!

**Comment by schalkneethling** [comment]
This has been merged in https://github.com/schalkneethling/all-aboard/commit/a7c9acd169d6f7625f3266e2883cce3e1525227a

**Comment by chrismore** [comment]
@schalkneethling I pulled down master and ran it locally and I don't see -moz or -fx added to the end of the utm_campaign. I'll drop a screenshot.

**Comment by chrismore** [comment]
![screen shot 2016-06-23 at 11 01 46 am](https://cloud.githubusercontent.com/assets/751491/16314336/2920f2ca-3932-11e6-9461-5aaf644b99e1.png)

**Comment by schalkneethling** [comment]
@chrismore You need to right click and select "Edit as HTML" to see the result. Not sure why, perhaps a bug in devtools.

**Comment by bniolet1** [comment]
I did the same and I also don't see the ammended parameters. Screen attached. 
![screen shot 2016-06-24 at 9 36 51 am](https://cloud.githubusercontent.com/assets/14222130/16339203/65b4300e-39ef-11e6-8e07-5d897c253f40.png)

**Comment by schalkneethling** [comment]
Hmmm, ok. Let me take a look.

**Comment by schalkneethling** [comment]
I just tested this locally, and here is what I see:

![screen shot 2016-06-24 at 16 45 48](https://cloud.githubusercontent.com/assets/10350960/16341065/91cbcbde-3a2b-11e6-9339-000ef0f88d0e.png)

@bniolet1 ^^

**Comment by bniolet1** [comment]
re-testing.

**Comment by schalkneethling** [comment]
@chrismore @bniolet1 Do we have any updates on this one?

**Comment by bniolet1** [comment]
From what I can tell, @chrismore was able to successfully subscribe an email address through the addon. 

Now that the addon first run is working again, I'm about to test again. Will advise shortly.

**Comment by chrismore** [comment]
Testing this out again now

**Comment by chrismore** [comment]
The -fx track seems to work fine with my testing.

**Comment by chrismore** [comment]
@schalkneethling ok, it looks like you need to append -fx or -moz to both the iframe src campaign parameter AND the data-src URL.

**Comment by schalkneethling** [comment]
@chrismore pr to complete this - https://github.com/mozilla/all-aboard/pull/198

**Comment by FrancescoSTL** [comment]
Fixed in #198
