### ISSUE TITLE
Update onboarding questions

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#355]
Based on feedback from usertesting.com we will update the onboarding questions for v1.2.

Have you used Firefox in the last 30 days? [unchanged]
Yes _[replaces "yup"]_
No _[ replaces "nope"]_

What interests you most about Firefox? _[replaces "Are you more"]_
It's built for people and not profit _[replaces "do good"]_
Its features and capabilities _[replaces "do it yourself"]_

Answering these two questions will help us customize your experience. _[replaces Your web your way. Help us set up Firefox just the way you want it]_

rough mockup:
![onboard-question-update](https://cloud.githubusercontent.com/assets/19597198/18576142/97607a28-7b93-11e6-93ec-4c40f07194b7.JPG)

**Comment by chrismore** [comment]
@fabiorios "not profit" vs "non profit" ?

**Comment by chrismore** [comment]
p.s. these questions get at the same basic thing we were trying to do with the previous questions, but are much less vague and confusing.

**Comment by chrismore** [comment]
@schalkneethling the "it's build for people... = values and its features...  = utility.

I can probably make this change directly as it is just html copy and no logic change.

**Comment by schalkneethling** [comment]
@chrismore I can get a quick PR in to do that

**Comment by schalkneethling** [comment]
PR: https://github.com/mozilla/all-aboard/pull/357

**Comment by fabiorios** [comment]
@chrismore let's keep as is: "...not profit". 

We do a good job of saying "non-profit" later, so not worried about the "not-for-profit" vs "non-profit" distinction here.

**Comment by schalkneethling** [comment]
@fabiorios makes sense to me as well in the context

**Comment by chrismore** [comment]
@fabiorios sounds good

**Comment by fabiorios** [comment]
@schalkneethling, I believe I'm looking at the latest file, if so just two minor adjustments needed. 

Change "yup / nope" to "Yes / No" (capitalize first letter)
On second question, change colon to question mark

![onboard-question-update2](https://cloud.githubusercontent.com/assets/19597198/18637106/26a5f272-7e40-11e6-9c21-8b42d34444ea.JPG)

**Comment by chrismore** [comment]
Looks good now
