### ISSUE TITLE
Snippet button misaligned on two snippets

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#364]
Content #1 values track: move button below snippet
Content #3 utility track: move button below snippet

@schalkneethling using jpm, I can't progress the utility track snippets to confirm if any of the other content pieces are misaligned. I was able to progress the values track by clearing my cache.

**Comment by schalkneethling** [comment]
Will take a look at this.

**Comment by schalkneethling** [comment]
This has been resolved. @fabiorios for the utility track, remember that the copy for all of the steps are the same so, the only way to confirm that the content is progressing is to click on the 'Check it out' button for each new step.
