### ISSUE TITLE
Notification and chrome icon not clickable

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#375]
When the notification fires, clicking it does not open the sidebar. Likewise, clicking the trophy icon in the chrome does not open the sidebar. 

Steps to reproduce: 

1. Windows 10
2. Delete all Firefox profiles. Uninstall Firefox. [Download and run f88](https://archive.mozilla.org/pub/firefox/candidates/49.0-candidates/build4/funnelcake88-testing/v3/win32/en-US/Firefox%20Setup%2049.0.exe)
3. Install Firefox. 
4. Answer "Yup" and "Do it yourself" (whatever the new version of that language is). 
5. Click "no thanks" on account form. 
6. First run completes. 
7. Set system clock ahead two hours. 
8. Wait for notification. 
9. When notification fires, click it. (nothing happens, expected: sidebar should open). 
10. After notification, click the trophy icon in the chrome. (again, nothing happens. expected: sidebar should open). 
11. Bonus: qa: advance system clock ahead two more hours. Wait for notification. Trophy icon is now gone from the Chrome.

**Comment by fabiorios** [comment]
I can replicate on W7. 

I'm unable to launch the sidebar by clicking on the tropy icon. I'm not getting the notification at all.

Also, onboarding snippets are not appearing.

**Comment by bniolet1** [comment]
I can confirm both that the notifications dont' launch unless you close and re-open Firefox. 

Snippets are not appearing for me, either. @schalkneethling do you want separate issues for all of this (kind of feels like the same cause for all of it, to my untrained brain).

**Comment by bniolet1** [comment]
Also I have reproduced this behavior: to get notification to appear, you must close and then re-open Firefox. Still not clickable.

**Comment by bniolet1** [comment]
Also I an confirm this behavior on W10 regardless of how you answer the golden question.

**Comment by bniolet1** [comment]
![image](https://cloud.githubusercontent.com/assets/14222130/18679791/288f0322-7f2f-11e6-9d02-a998c258a5b8.png)
After closing and re-opening Firefox, the notification that fires is the final one. This would explain why the add-on is self destructing if you close and reopen a second time.

**Comment by schalkneethling** [comment]
Time to bake a new cake :)
