### ISSUE TITLE
Build sidebar that shows some of the user's browser data

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#38]
Sidebar 5 for browser data migration

## Flow
User loads Firefox for the first time
Their browser data is auto-migrated using the auto-migration tool
The user is shown some of their browser history, bookmarks, and websites where they have saved their passwords in other browsers

**Comment by schalkneethling** [comment]
As mentioned elsewhere, you wanna have a look here https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/places_history and here https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/places_bookmarks for this sidebar

**Comment by FrancescoSTL** [comment]
Thanks @schalkneethling! I got the functionality working yesterday. Now I am working on the algorithm used to select which top history/bookmark's to show the user that we have imported.

**Comment by FrancescoSTL** [comment]
Update: apparently the low level API's for grabbing history don't contain all the info we want. We are looking to replicate something with a title, potentially an image, etc. Like this: 
<img width="595" alt="screen shot 2016-06-08 at 10 40 23 am" src="https://cloud.githubusercontent.com/assets/9794516/15910848/aecc52be-2d81-11e6-8d29-64e1a4ebf16a.png">

In order to do that, I'dl need to figure out how to connect to the places database, a local sqlite database that is on the user's machine which contains cached history/bookmark data. The issue is, I'm not sure this information will be automatically entered to the db upon migrating data from the migration tool. My inclination is that it will not. Which brings us back to the original implementation...

**Comment by schalkneethling** [comment]
I don't know. I am kinda torn on this one. I would say showing a couple random bookmarks and some supporting copy stating all the things that has been auto imported is better. For me personally, I will find the fact that an add-on just grabs and displays my history concerning.

I am very privacy conscious, so perhaps it is just me but, there is a lot of education going on about privacy, and we are one of the biggest proponents so, more and more general users will be aware and might share my concern.

Is it not enough to just show a couple of the imported bookmarks and then copy that states something like: "You are all set and ready to go. We have imported you bookmarks, history, passwords from your default browser. It makes things feel just a little more like home."

Also, will there be a way to undo this if the user does not want it imported? Will we provide access to this from the add-on?

**Comment by FrancescoSTL** [comment]
For some reason, when some people download the latest XPI to test this, their latest bookmarks aren't showing up. However, it doesn't always happen. All the versions of Firefox on my machine are querying for bookmarks properly, and any new profile that is created on other machines seems to be working as well. I haven't been able to replicate the issue thusfar. I am thinking that it may be an issue that comes along with sync, extensions, or something else that users might add to their profile over time. We will see if I can replicate the bug to isolate this issue before the end of the day.

**Comment by chrismore** [comment]
@FrancescoSTL @schalkneethling the Firefox team have landed the auto import code in nightly and it will soon backported to firefox 47.0, but it is possible to test in nightly.

Instructions:

Gijs> it's behind a pref in nightly
<Gijs> specifically, browser.migration.automigrate
<Gijs> so you can create a new profile, toggle that pref to true, and then exit and restart with the "--migration" command line switch

As for the undo function, Gijs is still working on it for the end of the month.

One bit of logic for the undo, is sync is enabled, *don't* display the "Undo import" link at the bottom. Only display the button if sync is not enabled in Firefox.

**Comment by chrismore** [comment]
Modified about:newtab #189 instead of doing a sidebar.
