### ISSUE TITLE
Always reload about:home

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#382]
To ensure snippets show up, always reload about:home after modifying the snippet content

**Comment by schalkneethling** [comment]
Duplicate of https://github.com/mozilla/all-aboard/issues/384

**Comment by chrismore** [comment]
This is what v1.1 did:

try { if (tabs.activeTab.url === 'about:home' && !aboutHomeReloaded) { aboutHomeReloaded = true; tabs.activeTab.reload(); } } catch (e) { console.error("Could not reload snippet content: " + e); }

https://github.com/mozilla/all-aboard/blob/master/index.js#L1188

**Comment by chrismore** [comment]
and I see the same logic in v1.5:

https://github.com/mozilla/all-aboard/blob/all-aboard-1-5/lib/utils.js#L41

**Comment by chrismore** [comment]
Only difference I see is aboutHomeReloaded: false vs var aboutHomeReloaded = false and this.aboutHomeReloaded in the conditional.

**Comment by schalkneethling** [comment]
Yup, this will run as before on startup but, after that, if the page is kept open and not refreshed, the snippet will not automatically progress to the next step. If there was a way to have access to the worker of the PageMod, we could improve this situation but, as it stands now, I reckon we are doing all we can.
