### ISSUE TITLE
"next up" follow up text disappears

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#385]
1) start to go through onboarding
2) get to say step 3
3) click the stars to go back to previous steps
4) click CTA

Expected:

The follow up and next text below the stars should be there

Actual:

It is missing from some of the sidebars and specifically the first two. If you do this a few times, it will completely lose all of the stars and clicking the CTA will not give you a new star.

**Comment by schalkneethling** [comment]
Resolved by: https://github.com/mozilla/all-aboard/pull/388
