### ISSUE TITLE
Add-on self-destructs unexpectedly after Firefox closes

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#386]
Steps to replicate: 

Windows 10
Create a fresh profile and launch funnelcake build 88. 
Install latest xpi and trigger first run. 
Chose Utility track.
Close firefox. 
Set system clock ahead 2 hours. 
Re-open Firefox and wait approx 60 seconds for a notification. 
When it comes, click the CTA in the sidebar. 
Verify that your star has been rewarded
Close Firefox. 
Set system clock ahead by one day. 
Re-open Firefox. 
Add-on is still installed, but trophy is gone from the Chrome and notification never comes.

**Comment by bniolet1** [comment]
I can confirm this behavior on Values flow as well. 

After advancing the system clock a day and an hour or so, re-open Firefox. And wait. Notification def. does not come after 60 seconds and it does not come after several minutes.

**Comment by bniolet1** [comment]
This behavior occurs whether you engage with content or not.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mozilla/all-aboard/pull/387
