### ISSUE TITLE
Add-on destroys itself after 24 passes after 5 content without claiming prize

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#395]
Steps:

* engage with all by CTAs
* Advance clock forward 24 hours (or 26 until the current bug is fixed)

Expected:

* A notification and trophy icon still exists to tell me about my prize

Actual results:

No trophy icon and no notification. Looks like the destroy is being called.

**Comment by chrismore** [comment]
This is what v1.1 did:

`try {
        if (tabs.activeTab.url === 'about:home' && !aboutHomeReloaded) {
            aboutHomeReloaded = true;
            tabs.activeTab.reload();
        }
    }
    catch (e) {
        console.error("Could not reload snippet content: " + e);
}`

https://github.com/mozilla/all-aboard/blob/master/index.js#L1188

**Comment by chrismore** [comment]
and I see the same logic in v1.5:

https://github.com/mozilla/all-aboard/blob/all-aboard-1-5/lib/utils.js#L41

**Comment by chrismore** [comment]
Only difference I see is aboutHomeReloaded: false vs var aboutHomeReloaded = false and this.aboutHomeReloaded in the conditional.

**Comment by chrismore** [comment]
opps. wrong issue :-/

**Comment by chrismore** [comment]
Intervals should be 1/12 open auto (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders)

**Comment by schalkneethling** [comment]
Resolved by: https://github.com/mozilla/all-aboard/pull/399
