### ISSUE TITLE
Intervals set to 24 hours + 2 hours instead of 24 hours

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#396]
Steps to reproduce:

1) Install latest XPI into funnelcake
2) Answer questions
3) Advance forward 2 hours
4) get notification
5) Engage with CTA
6) Close Firefox
7) Advance forward 24 hours
8) Open Firefox
9) No notification received
10) Close Firefox
11) Advance forward 2 hours
12) Open Firefox
13) notification received

Expected:

Notification every 24 hours after the first 2 hour sidebar auto open.

Actual:

Notification every 26 hours. The 2 hours is being added on to each 24 hour base interval.

**Comment by chrismore** [comment]
Intervals should be 1/12 open auto (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders) > 24 hours  (then 2 24 hour reminders)

**Comment by schalkneethling** [comment]
There was not actually any hours added to the 24, the problem was this:

`timeSinceCTAComplete > intervals.defaultSidebarInterval` instead of `timeSinceCTAComplete >= intervals.defaultSidebarInterval`

So your interval would have to be greater than 24

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mozilla/all-aboard/pull/398
