### ISSUE TITLE
Notifications always triggered every session if you don't engage with CTA

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#407]
The requirements for v1.2 are that we should send one notification per content number and then two follow up reminder notifications (identical to the first) for a max of three. We also delay any notification for 60 seconds after Firefox opens.

The notifications is triggering every time you open Firefox after 60 seconds if you don't engage with the CTA. It doesn't matter if 24 hours has passed or not.

The notifications should be as follows:

Content 1:
1st: +2 hours
2nd: +24 hours after 1st if you don't click CTA
3rd: +24 hours after 2nd if you don't click CTA

Content 2:
1st: +24 hours after content 1 CTA click
2nd: +24 hours after 1st if you don't click CTA
3rd: +24 hours after 2nd if you don't click CTA

Content 3:
1st: +24 hours after content 2 CTA click
2nd: +24 hours after 1st if you don't click CTA
3rd: +24 hours after 2nd if you don't click CTA

Content 4:
1st: +24 hours after content 3 CTA click
2nd: +24 hours after 1st if you don't click CTA
3rd: +24 hours after 2nd if you don't click CTA

Content 5:
1st: +24 hours after content 4 CTA click
2nd: +24 hours after 1st if you don't click CTA
3rd: +24 hours after 2nd if you don't click CTA

Prize content
1st: +2 hours after content 5 CTA click
2nd: +24 hours after 1st
3rd: +24 hours after 2nd

Also, if you don't engage with a CTA, the add-on should destroy itself after 3 weeks.

**Comment by schalkneethling** [comment]
Resolved by: https://github.com/mozilla/all-aboard/pull/409 @chrismore please run this through it's paces.
