### ISSUE TITLE
Add-on doesn't destory itself after 3 weeks

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#408]
If you don't engage with the first or any following sidebar content CTA, the add-on should destroy itself after 3 weeks. This will prevent the icon sitting in the chrome for the lifespan of the user's experience with Firefox. Notifications should stop per issue #407, but this icon should go away after 3 weeks if you stop engaging for 3 weeks.

This needs to be tested with Firefox opening/closing as the timers reset.

**Comment by schalkneethling** [comment]
@chrismore ok, this one has landed as well: https://github.com/mozilla/all-aboard/pull/410

**Comment by chrismore** [comment]
@schalkneethling Almost completely works.

The icon is being removed, the notifications do stop, but the snippets are still being injected after destroy() is being called.

See: https://cl.ly/3z473D2B1p0G

There is no css, but the snippets are still being injected. If I disable the add-on within about:addons, this no longer happens. If if re-enable the add-on, this happens when Firefox is first opened.

**Comment by chrismore** [comment]
Also, you can't click on the button seen in the screenshot. Nothing happens as expected.

**Comment by schalkneethling** [comment]
Yup, makes complete sense actually. If you have about:home open at the time the add-on is destroyed, it will receive the destroy intent but, destroying "Modifications already made to open documents by content scripts will not be undone, but stylesheets added by contentStyle or contentStyleFile, will be unregistered immediately." - https://developer.mozilla.org/ja/Add-ons/SDK/High-Level_APIs/page-mod#destroy()

If the page is not open, it will not receive the destroy at all and might in future simply execute as if the add-on is still active.

Will have to do a couple of things here.

1. We need to store a flag that indicates that the add-on has been destroyed.
2. For all pageMods we need to check whether this flag exists and is true
3. For about:newtab and firstrun, we can just do a sanity call to `destroy` but those are only run conditionally and so, even if not destroyed, will not do anything in future.
4. For about home, we need to call destroy and refresh the page again to get rid of the snippet we injected

**Comment by schalkneethling** [comment]
@chrismore Resolved by https://github.com/mozilla/all-aboard/pull/415
