### ISSUE TITLE
Provide CSS changes to be applied to sticker form

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#424]
For the new design there are some changes that needs to be incorporated into the remote sticker form. This issue is to track and provide the details so it can be relayed to the relevant parties by @fabiorios

**Comment by fabiorios** [comment]
I'll see if I can get a generic URL for us to work out the design.

**Comment by schalkneethling** [comment]
Thx @fabiorios - One question I have is, are there still any experiments live out there? The reason I ask is, if we change the design of the form, it will change for everyone irrespective of the version of the add-on they are running. We just need to keep that in mind.

**Comment by schalkneethling** [comment]
These are the first changes they can make:

```
body {
    margin: 0;
    background-color: transparent;
    font-family: inherit;
}
```
No need for them to provide a custom font, they can just inherit.

**Comment by schalkneethling** [comment]
Loading a custom font will slow things down, and this one of the few places we load something via the web.

**Comment by fabiorios** [comment]
@schalkneethling they've implemented our changes on a test form. here it is: https://mozillatest.thinksmart.com/

**Comment by schalkneethling** [comment]
Got it

**Comment by schalkneethling** [comment]
Added new form and privacy to the final sidebar - https://github.com/mozilla/all-aboard/pull/449

**Comment by fabiorios** [comment]
@schalkneethling 

we need to revert back to the original URL (https://mozilla.thinksmart.com/). Thinksmart will update the CSS on Monday.

Also, the privacy copy needs to be updated it should read:

This is the only thing we'll ever send you. Read our Privacy Policy.

Lastly, the privacy copy looks misaligned on my screen check it out:

![sticker-left](https://cloud.githubusercontent.com/assets/19597198/20453356/0d587efe-add7-11e6-8586-ee211fafc8d8.JPG)

**Comment by chrismore** [comment]
@schalkneethling Please update the iframe URL to https://all-aboard-remote.herokuapp.com/

The heroku app then does a 301 redirect to http://mozilla.thinksmart.com/

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mozilla/all-aboard/pull/456
