### ISSUE TITLE
Update snippet copy for v1.5

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#436]
Snippets need minor adjustments to line up with new sidebars. I've taken the headline of each sidebar and added our default text from v1.2. 

@schalkneethling Here's the set:

Snippet 1 - Welcome to freedom. Master Firefox and get a gift. 
Snippet 2 - Fight back against trackers. Master Firefox and get a gift. 
Snippet 3 - Don't settle when searching. Master Firefox and get a gift.
Snippet 4 - Roam free. Master Firefox and get a gift.
Snippet 5 - Claim your gift now!

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mozilla/all-aboard/pull/439
