### ISSUE TITLE
Update notification copy for v1.5

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#437]
@schalkneethling Notifications 2, 4, 5 need to be updated and the final notification is blank. Here’s what they should be:

1. Earn stars. Get a gift. Check it out.
2. Three stars stand between you and your gift. Click here.
3. Reach the trophy. Get your gift. Check it out.
4. Almost done! Your gift awaits. Check it out.
5. Claim your prize! Click here now.

**Comment by schalkneethling** [comment]
Fixed by https://github.com/mozilla/all-aboard/pull/438
