### ISSUE TITLE
Polish sidebar copy

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#446]
@schalkneethling we've got some last minute clean up and minor copy change.

 1) Adjust line breaks so we don't orphan words/lines: https://docs.google.com/document/d/1TBWTmwwBeWQDaBM6sKu06t6vt8CAwnw_OidI1Z_M5v8/edit

2) sidebar 1/scene 2 copy change: "The trophy means a gift is involved." CHANGE TO: Unlock all 4 for a free gift.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mozilla/all-aboard/pull/447
