### ISSUE TITLE
Content 1 sidebar has scroll bars

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#458]
When viewed at 1366 x 768, sidebar one has vertical and horizontal sidebars whereas content 2-4 does not. What is different about content 1 that is causing it to be taller and wider than the rest?

https://github.com/mozilla/all-aboard/blob/all-aboard-1-5/data/tmpl/sidebars/content1.html

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mozilla/all-aboard/pull/460 - Although I could not replicate the horizontal scrollbars, I was able to replicate the vertical.
