### ISSUE TITLE
Claim your gift text is difficult to see

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#459]
When viewed at the most common windows resolution, "Claim your gift now -->" is right above the bounding fox and the contrast makes it really hard to see. I'd probably move the link about 50 pixels up and closer to the mobile buttons so it it doesn't overlap the fox and get into the lighter part of the background.

**Comment by chrismore** [comment]
![20161122_160925](https://cloud.githubusercontent.com/assets/751491/20547023/33af754a-b0ce-11e6-851f-46bcdcdf4f34.jpg)

**Comment by chrismore** [comment]
I wonder if we should also make the text dark grey too.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mozilla/all-aboard/pull/461

![screen shot 2016-11-23 at 11 40 12](https://cloud.githubusercontent.com/assets/10350960/20557252/72eae2bc-b173-11e6-888c-f887647e54d3.png)

**Comment by ternstyles** [comment]
I think the dark text is a decent compromise here. It is a unique CTA so it can break from the previous styled CTAs.
