### ISSUE TITLE
about:home

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#46]
@chrismore - I was wondering, what is the interaction model we expect for users when it comes to about:home? What I mean is, other than when a user clicks on 'No thanks', what are the other scenarios that will take them there?

Is this simply when they type about:home into the address bar or, perhaps after a restart? In general after a restart, a user's last session's open tabs are shown. Not entirely clear on this one.

**Comment by chrismore** [comment]
@schalkneethling I just updated the flow diagram to make about:home a bit more clear.

https://mana.mozilla.org/wiki/display/EN/Onboading+Add-On+Flow+Diagrams

The only two different types of interactions that we need to worry about with about:home.

1) On the first installation of Firefox, we show the data sidebar on about:home.

2) On any future session of Firefox, the only thing we need to worry about with about:home is that the snippet content is aligned with whatever content is in the sidebar. 

On first run of Firefox, here's the basic logic:

* Clicking "no thanks" on the questions gets you to about:home, but onboarding is over forever for you. No sidebars no snippets, not anything else.

* Clicking "no thanks" on the FxA form, sends you to about:home, but you still get the data sidebar and snippets.

* If a user navigates away from the FxA form and they have answered the questions, they do *not* get about:home as the sidebar simply opens on whatever website they are on.  

Go through the flow again and ensure it all makes sense. All of the top flow is *only* for first run and all of the second half of the flow starts on the second green circle where it says "user starts new session after first run".

**Comment by schalkneethling** [comment]
> 1) On the first installation of Firefox, we show the data sidebar on about:home.
@chrismore  correct me if I am wrong, the first snippet will only start to override the default along with the first content sidebar i.e. 24 hours after the data imported sidebar is shown.

**Comment by chrismore** [comment]
@schalkneethling correct. Snippets will only start to override when new content is available, i.e. when the notification happens.
