### ISSUE TITLE
Auto build xpi

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#52]
I was thinking that we probably want the `.xpi` on master reflect the most recent work merged to master. Currently we are building it on demand, randomly, and adding it to the repo.

Might be worth to link this to circle-ci and have it build a new xpi every time we merge new code. Thoughts?

@chrismore @FrancescoSTL

**Comment by chrismore** [comment]
@schalkneethling that seems to make sense to me.

**Comment by FrancescoSTL** [comment]
Yep, I think this would be good.

**Comment by chrismore** [comment]
makes sense to me

**Comment by FrancescoSTL** [comment]
@schalkneethling I'm thinking it might be worth pushing back to milestone v1, as it isn't necessary we complete it for this sprint. If it only takes a few min, we might want to keep it, though. Thoughts?

**Comment by schalkneethling** [comment]
@FrancescoSTL This is pretty quick and simple. I will hook it up tomorrow.

**Comment by FrancescoSTL** [comment]
@schalkneethling cool, thanks 😄

**Comment by schalkneethling** [comment]
Done, latest XPI is now build on merges to master.

![screen shot 2016-06-28 at 13 05 47](https://cloud.githubusercontent.com/assets/10350960/16413230/0c9d89bc-3d31-11e6-812f-acbf796f036c.png)

**Comment by schalkneethling** [comment]
This turned out to be a hell of a thing :-/ I believe I am there now, or almost. Either way, here is where the latest XPI will live:
https://github.com/mozilla/all-aboard/tree/dist

**Comment by FrancescoSTL** [comment]
Is this the expected result for PR's, being that we haven't set up any tests?
<img width="789" alt="screen shot 2016-06-28 at 9 35 35 am" src="https://cloud.githubusercontent.com/assets/9794516/16424132/bfe85cb8-3d13-11e6-88ae-a2d4a671fc4e.png">
