### ISSUE TITLE
FxA form is Sign Up, not sign in

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#541]
This is the latest funnelcake, tested on 2.24.17.

![2017-02-24](https://cloud.githubusercontent.com/assets/14222130/23315043/72c1227a-fa92-11e6-87c0-edd03202243a.png)

**Comment by JennyDouglas** [comment]
This is supposed to be Sign up not sign in.

**Comment by bniolet1** [comment]
Testing doc said otherwise. I'll close this.

**Comment by JennyDouglas** [comment]
We decided a couple of weeks ago that it did no make sense to change this to Sign in, since all the AB testing has shown that sign in creates about 50% less accts

**Comment by schalkneethling** [comment]
@bniolet1 Are you using these docs? https://github.com/mozilla/all-aboard/wiki/Testing-firstrun
