### ISSUE TITLE
Sidebar for user reward

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#62]
As a Firefox user who answers questions on my first experience, I’m excited to know that Mozilla is sending me a sticker for my continued use, so that I know they value me as a user.

**Comment by chrismore** [comment]
![reward](https://cloud.githubusercontent.com/assets/751491/16318678/09fe80ca-3945-11e6-8332-7d7a8d29585e.png)

![confirmation](https://cloud.githubusercontent.com/assets/751491/16318684/0e917ed0-3945-11e6-8d95-7d1d0a560e1b.png)

Screenshots for the reward sidebar.

Copy: https://docs.google.com/document/d/1Fzxe-Y2ZOheJ0vFFjcQxAiofOWMWgBfjWgeG4gTtP-g/edit#heading=h.abe9k69byvek

**Comment by callahad** [comment]
Noticed on Reddit: https://www.reddit.com/r/firefox/comments/57pgcd/i_was_working_on_a_clients_computer_downloading_a/

Also, we missed the user story of "As a remotie who doesn't get to the offices all that often, I want the opportunity to get legitimate swag every once in a while so I don't have to coerce Potch into stealing it for me from the bountiful fields of Mountain View."
