### ISSUE TITLE
Snippet for user reward

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#63]
As a Firefox user who answers questions on my first experience, I’m excited to know that Mozilla is sending me a sticker for my continued use, so that I know they value me as a user.

**Comment by fabiorios** [comment]
@schalkneethling here are the three. We'll hyperlink the entire line.

Thanks for sticking with Firefox!

Browse Free or Die! Get yours!

Have you claimed your gift?

**Comment by ternstyles** [comment]
Below are examples of the snippets within the setting

![reward-snippet_onscreen_v1](https://cloud.githubusercontent.com/assets/20114656/16468704/3a1ded88-3e1b-11e6-8e8b-0a581dfc8424.png)
![reward-snippet_onscreen_v2](https://cloud.githubusercontent.com/assets/20114656/16468705/3a236fec-3e1b-11e6-9f8d-4a26a23eb5d7.png)
![reward-snippet_onscreen_v3](https://cloud.githubusercontent.com/assets/20114656/16468706/3a275c88-3e1b-11e6-8e89-91e1bca1e50d.png)

**Comment by ternstyles** [comment]
Actual 64x64px snippet attached.

![reward_snippet_64x64](https://cloud.githubusercontent.com/assets/20114656/16468732/5497b8f6-3e1b-11e6-8628-96b03f4398e5.png)

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL this snippet image needs to be 50px by 50px. Francesco did the snippet resign issue with on Friday with me and we had to make a number of adjustments to make it look similar. I would follow the same CSS and 50px max image size like the other snippets.

**Comment by schalkneethling** [comment]
@chrismore will do. Thanks for the heads up.

**Comment by schalkneethling** [comment]
@chrismore Looking at the snippets I am seeing that most of the snippets' action are things that *do* things, not so much *navigate* somewhere. I really do not feel leaving of the `href` from an anchor element is good practice(it also break a11y), nor do I like the value being something non valid like `#0` or something.

I would therefore propose that we use anchor element when the action navigates the user to a different page and use a button element, when the action does something.

I would also not suggest we style buttons to look like links, I therefore propose the following styling for when the action calls for a button.

![screen shot 2016-07-04 at 21 00 05](https://cloud.githubusercontent.com/assets/10350960/16568475/e4e852ae-422a-11e6-9ef5-e6fd6e6226d4.png)

P.S. In the above case we would of course just have a plain like, just using it for demonstrative purposes. Let me know your thoughts. Thanks!

**Comment by chrismore** [comment]
@schalkneethling good point and that's kind of what we discussed on the sidebar strategy before. links = navigate somewhere else. buttons = change the current UI. 

With the snippets, they are about half and half where some are going somewhere and others open up a UI. I think the only reason we did links is to not spend anymore time on the design/css and just needed to get something fully functional on Friday. 

I would be fine with anything that changes the UI (like the UITour stuff) is a small button and anything that takes you somewhere else is a link. As long as the buttons are small-ish and nowhere as big as the button in the sidebar. We could probably just put the buttons on a separate line below the text snippet left aligned and text links inline as the end or final sentence in the snippet. That would follow the current design standards for snippets already.

**Comment by schalkneethling** [comment]
@chrismore Thanks for the feedback. So, you would prefer the buttons be on a new line, left aligned as apposed to inline as in the screenshot I posted in comment https://github.com/mozilla/all-aboard/issues/63#issuecomment-230342827

**Comment by chrismore** [comment]
@schalkneethling yeah, because i believe that's how other buttons are on the snippet service. You only do in-line when it is a link and not, you put the button below left or center aligned. I think for these, left-aligned below the text is best. Just make sure the button is probably 25% smaller than the sidebar buttons. thanks!

**Comment by andreicristianpetcu** [comment]
You should do a similar sticker for Nightly users :D

**Comment by HammyHavoc** [comment]
As someone who uses Activity Stream and seldom ever sees this view, I hope I'm going to be offered a sticker. :- )
