### ISSUE TITLE
Make badges clickable

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#64]
There will be 5 badges at the bottom and you will receive one for each content element excluding the first run data import. The items should be clickable to go backwards, but not forward. If you do go backwards and close a sidebar and re-open it, it should show the latest content and not the one you scrolled back to from clicking the badge.

Also, please ensure if you click on other badges and go back to older ones that the distribution.id does NOT change.

**Comment by chrismore** [comment]
@schalkneethling what's the status of this? we need to get this merged today to be able to get the P2s on Friday.

**Comment by FrancescoSTL** [comment]
Merged
