### ISSUE TITLE
Implement new icon and icon states

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#66]
This is the tracker to implement the new icon as designed by Matt. I know there was a discussion about the different states, green, yellow, gray but, I cannot remember all the details. @chrismore was this noted down somewhere?

**Comment by schalkneethling** [comment]
@chrismore I was thinking that, until the user has completed the questions and the import(data imported) sidebar is shown, the add-on should be disabled. Thoughts?

**Comment by FrancescoSTL** [comment]
Once this issue is solved, issue #80 should be nullified, assuming we disable the add-on before the import sidebar completed or exited.

**Comment by chrismore** [comment]
@schalkneethling correct. If they didn't answer the 2 questions on first run, the add-on stays disabled and they don't get onboarding. The onboarding is only for people who have answered both questions. If they answer the questions, the sidebar will be show regardless of what you do next.

**Comment by schalkneethling** [comment]
Ok so, add-on icons stays disabled until the data import sidebar is shown. Noted.

**Comment by schalkneethling** [comment]
[light-bulb-icons.zip](https://github.com/mozilla/all-aboard/files/320135/light-bulb-icons.zip)

New add-on icon

**Comment by FrancescoSTL** [comment]
Can close on merge of #194
