### ISSUE TITLE
Update snippets layout

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#67]
The layout of the current snippets needs to be updated the follow the standard snippet format i.e.
Icon on the left, copy, links, and buttons to the right.

![screen_shot_2016-06-14_at_12 15 02_pm](https://cloud.githubusercontent.com/assets/10350960/16046870/35bd813c-324e-11e6-97b9-09035425e0e0.png)

**Comment by chrismore** [comment]
@schalkneethling see the screenshot column for the layout of all of the snippets. Matt will send the raw 64x64 gifs for each snippet too.

https://docs.google.com/document/d/1Fzxe-Y2ZOheJ0vFFjcQxAiofOWMWgBfjWgeG4gTtP-g/edit#heading=h.99gb7ft31sdr

**Comment by ternstyles** [comment]
Utilities snippets:
https://www.dropbox.com/s/9f3m2h0nclabjla/utility_snippets_64x64px.zip?dl=0

Values snippets:
https://www.dropbox.com/s/ioz8ufkcxq5wxxq/values_snippets_64x64px.zip?dl=0

**Comment by FrancescoSTL** [comment]
Fixed in #248
