### ISSUE TITLE
Snippets copy rotation

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#68]
Each snippet that forms part of the add-on contains three pieces of copy. These need to be shown on rotation so that the user does not see the same piece of copy over and over for each 24 hour period.

The CTA and icon remains the same though.

**Comment by chrismore** [comment]
New layout is also in #67

**Comment by chrismore** [comment]
Handled in PR #248

**Comment by FrancescoSTL** [comment]
Fixed in #248
