### ISSUE TITLE
Re-open sidebar when notification is received and sidebar is open

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#78]
If you have the sidebar open and you get a notification, clicking it closes it, which is a bad user experience since the notification doesn't give you anything.

Since we can't change the state of the sidebar while open, we'll have to close it and re-open it when this state occurs. 

Proposed Logic:

If sidebar.open && notification.received then {
   sidebar.close;
   sidebar.open;
}

**Comment by FrancescoSTL** [comment]
In the current version (after merging the two most recent PR's) this issue still exists. One other thing to note in a similarly related bug, whenever there is no notification, clicking the badge throws a "sidebarprops is undefined" error. I'll file a separate issue for this.
<img width="854" alt="screen shot 2016-06-15 at 1 46 02 pm" src="https://cloud.githubusercontent.com/assets/9794516/16080339/37712d96-3300-11e6-8a6f-f369b045cfaf.png">

**Comment by schalkneethling** [comment]
@FrancescoSTL Just double check that you are up to date with the latest master also, there is a pull request that fixes this issue: https://github.com/mozilla/all-aboard/pull/81

**Comment by FrancescoSTL** [comment]
Yep, I am up to date with the latest master. I'll check out the PR shortly!

**Comment by schalkneethling** [comment]
@chrismore Can you confirm that this is resolved? Thanks!

**Comment by schalkneethling** [comment]
@chrismore Please confirm that this is resolved after https://github.com/mozilla/all-aboard/pull/105 merges. There is still issue https://github.com/mozilla/all-aboard/issues/85 which will be handled separately. Thx

**Comment by chrismore** [comment]
@schalkneethling fixed now!

**Comment by schalkneethling** [comment]
\o/
