### ISSUE TITLE
Show badge when clicking sidebar cta

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#79]
This probably makes more sense than just making it show up even though we have gone back and forth on it.

Utility side

* search button
* PB open button
* highlight awesomebar button
* trying any theme
* clicking any of the mobile buttons

Values side:

* Clicking the "tell me" button

**Comment by schalkneethling** [comment]
@chrismore Badge as in token aka the icons at the bottom? So we are not giving them simply for opening the sidebar, they need to take action?

**Comment by FrancescoSTL** [comment]
@schalkneethling Yep! We discussed with Matt in person and are reverting to adding a token when the action is taken

**Comment by chrismore** [comment]
yeah, let's change it so that the button tokens/badges only show up after you click a button. Seems like something badge-worthy than just showing it immediately.

**Comment by schalkneethling** [comment]
Ok, so based on discussions, we are changing the awarding of tokens as follows:

Tokens are now only awarded when the user takes the relevant action presented by the sidebar(See https://github.com/mozilla/all-aboard/issues/79#issue-160411651 for details)

New timers are also only started once the user has taken the above action and not before i.e. not when the sidebar is opened.
