### ISSUE TITLE
Award tokens buggy

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#82]
It seems the award tokens are a little buggy. This might be a timing issue with simple-storage but, they do not show up consistently.

**Comment by schalkneethling** [comment]
This will be resolved by https://github.com/mozilla/all-aboard/issues/79 and https://github.com/mozilla/all-aboard/issues/86

**Comment by schalkneethling** [comment]
@chrismore @FrancescoSTL Please confirm that this is resolved after https://github.com/mozilla/all-aboard/pull/105 merges. Thx

**Comment by FrancescoSTL** [comment]
Fixed in #105
