### ISSUE TITLE
Add Google Analytics events to /firstrun/ HTML code inection

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#83]
We'll need to work with Peter and Gareth on getting what variables to inject into the HTML:

Events:
- answering yup or nope to new/existing user question
- answering the do good vs do it yourself question
- clicking no thanks

We shouldn't need anymore events since the FxA form already has events on it.

**Comment by chrismore** [comment]
@garethcull

**Comment by schalkneethling** [comment]
Do we want to do this in 1.5? @chrismore

**Comment by chrismore** [comment]
@schalkneethling it would be nice to know the distribution up front, but we do get this from telemetry already so it is kind of a nice to have. Let's hang on to it.
