### ISSUE TITLE
Add Theme Images Locally

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#84]
Users on a slow connection (such as myself currently at MozLondon 😏) will have trouble viewing the theme sidebar, as loading the theme images takes a while and nothing shows up in the meantime. I'm thinking the best fix for this is to add the files to the add on locally. The only downside to this is increasing the size of the xpi, but it will likely be negligible.

**Comment by schalkneethling** [comment]
So, there are a couple of positives regarding the size of the add-on. As it is shipped with Firefox, the user does not download and install it, with that said though, we can not just arbitrarily bloat the size of Firefox.

Do you know what the size will be of having those locally? Also, might there be an issue with Firefox blocking us if we try and "install" a theme that way?

The alternative is to add a simple loading graphic that we show as soon as the user clicked the button to try one of the themes. At least this way, they are aware that they clicked registered and something is happening.

**Comment by FrancescoSTL** [comment]
@schalkneethling I was thinking this when I developed the feature starting out, however, I'm not sure it is the best play any longer. We'd be looking at ~50kb per theme, which isn't a whole lot in the grand scheme of things. The theme that we are requesting from AMO is simply an object with various parameters such as author, header color, footer color, etc. The ones we are interested in are the header, footer, and preview image URL's. For this reason, I wouldn't think that Firefox would have any issue with this but I will test shortly and update.

**Comment by FrancescoSTL** [comment]
Installing themes locally is working. It will look something like:

` var url = self.data.url("./media/FoxFF.jpg");
    var theme = {"username":"jbhphx","description":null,"detailURL":"https://addons.mozilla.org/en-US/addon/fox-in-snow/","accentcolor":"#ffffff","iconURL":"https://addons.cdn.mozilla.net/user-media/addons/111387/preview_small.jpg?1270135366","previewURL":"https://addons.cdn.mozilla.net/user-media/addons/111387/preview.jpg?1270135366","textcolor":"#000000","id":"111387","headerURL":url,"dataurl":"","name":"Fox in Snow","author":"jbhphx","updateURL":"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/111387","version":"0","footerURL":"https://addons.cdn.mozilla.net/user-media/addons/111387/FoxFooter.jpg?1270135366"};
    LightweightThemeManager.themeChanged(theme);`

**Comment by FrancescoSTL** [comment]
Additionally, we can attempt to store the entire object in memory and see if that reduces load time. I'm sure slow load time is a combination of requesting the object from AMO and requesting the image from AMO (separately).

**Comment by FrancescoSTL** [comment]
Close in favor of #95
