### ISSUE TITLE
Trigger start timer when a badge is displayed (clicking CTA in sidebar)

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#86]
With this new logic: https://github.com/mozilla/all-aboard/issues/79 we need to change the timer start so that it only starts once a badge if given. If we don't, a user could make it to the end by simply clicking the desktop notification, engaging with noting, receiving no badges, and we give them a sticker, which seems like false engagement.

**Comment by FrancescoSTL** [comment]
Merged in #111
