### ISSUE TITLE
Sign Add-On

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#87]
Mike Kaply said it is easy. He can drop the info here.

**Comment by chrismore** [comment]
@mkaply can you let us know what we need to do to get this add-on signed when finish up development?

**Comment by mkaply** [comment]
Is this add-on going to be checked into Firefox or just done as a Funnelcake add-on?

**Comment by chrismore** [comment]
> Is this add-on going to be checked into Firefox or just done as a Funnelcake add-on?

Just a funnelcake add-on, you won't be able to find this on addons.mozilla.org.

**Comment by mkaply** [comment]
And I assume there won't be any need to update it.

So you'll want to create an account on addons.mozilla.org and then submit the add-on to be signed as an unlisted extension. It can be as simple as a team account or something like that. It can even be a personal account, but you'll want to make sure to assign a second owner of the add-on just in case.

**Comment by schalkneethling** [comment]
Here is the info:
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign

**Comment by chrismore** [comment]
I've created an AMO account called growth-team@mozilla.com

I have generated the API keys and I will email to @schalkneethling and @FrancescoSTL.

**Comment by chrismore** [comment]
@mkaply I have generated the API keys and sent them to the devs. The issue is that we are not done with the XPI completely yet. Is the signing pretty quick turn around via the jpm_sign @schalkneethling mentioned above?

**Comment by mkaply** [comment]
Yes, signing is immediate.

Mike

**Comment by chrismore** [comment]
Immediate = good. thanks!

**Comment by chrismore** [comment]
@schalkneethling can you attempt to sign the add-on with the keys I emailed you? The release engineering team asked us to get the add-on signed now while we are still in QA to speed up their process.

**Comment by schalkneethling** [comment]
@chrismore I am getting "response: {"detail":"Signature has expired."}"

**Comment by chrismore** [comment]
Talked to @mkaply and he's checking with AMO now.

**Comment by mkaply** [comment]
@EnTeQuAk requesting your help :)

**Comment by chrismore** [comment]
Should @schalkneethling do a jpm --version to make sure we know what version he is using to sign? I am currently running 1.0.7 locally.

**Comment by EnTeQuAk** [comment]
Yeah, please make sure to use the latest jpm version and correct api-keys from AMO. Also make sure that your system-clock is in sync.

**Comment by chrismore** [comment]
I created an account on AMO for the growth-team@mozilla.com email and went here https://addons.mozilla.org/en-US/developers/addon/api/key/ and grabbed the keys and emailed them to @schalkneethling last week.

**Comment by schalkneethling** [comment]
I am running 1.0.7 as well

**Comment by schalkneethling** [comment]
Tried again, still getting the same error. Could the fact that I am trying to sign it from South Africa make a difference? (wild idea but, seeing system clock can be an issue). Perhaps it needs to be done on the same machine that downloaded the keys?

@chrismore Is there a way to regenerate the key(s) perhaps?

**Comment by EnTeQuAk** [comment]
Well, then I wouldn't be able to sign it here from Germany too since our servers are in the US. But what timeserver are you using? It can still be that your system time is drifting too much.

The keys that are downloaded are only used to generate the signature on the client so a regeneration of those keys probably won't fix anything. But worth trying nonetheless maybe.

**Comment by chrismore** [comment]
@schalkneethling do you want to try creating your own AMO account, going to https://addons.mozilla.org/en-US/developers/addon/api/key/, getting a new set of keys and see if that makes a difference? Probably worth a try.

**Comment by schalkneethling** [comment]
@chrismore let me give that a go

**Comment by FrancescoSTL** [comment]
I was able to sign the addon in its current version. @chrismore ping me whenever you need an xpi signed!

**Comment by chrismore** [comment]
It is an important note that whatever we call the add-on when signing it has to match what nthomas calls the folder in the funnelcake config. Currently, @FrancescoSTL has the add-on called all-aboard-dev since there is an AMO bug that if you have deleted an add-on, it is still listed, and if you try to sign a new add-on with the same name it says there is an existing add-on already listed. Since you can't un-delete the deleted add-on, you are stuck and you have to name the add-on something else.

**Comment by schalkneethling** [comment]
Would it help if we incremented the version number when signed?

> Your add-on at this exact version number already exists, so it was not signed. Increment the version number in your package.json file and run the command again.

**Comment by schalkneethling** [comment]
This is done? @chrismore @FrancescoSTL

**Comment by chrismore** [comment]
Done!
