### ISSUE TITLE
JS Cleanup Part 1

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#89]
The functions `getHistory(worker);` and `getBookmarks(worker);` has a lot in common, after out first deadline, we should look at creating one utility function that can be used by both, passing only what is unique to the utility.

**Comment by FrancescoSTL** [comment]
Also, implement the UITourHelper rather than having showmenu, highlight, showbookmarks, etc: https://github.com/mozilla/all-aboard/pull/212#discussion_r69297148

**Comment by schalkneethling** [comment]
@FrancescoSTL I think we can close this one as we will be doing this as part of changing to web extensions. Thoughts?

**Comment by FrancescoSTL** [comment]
@schalkneethling Maybe we move to tracking? We will likely still have js we can condense when we port over IMO

**Comment by schalkneethling** [comment]
+1
