### ISSUE TITLE
Optimize layout of user data sidebar

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#90]
There was a discussion here https://github.com/mozilla/all-aboard/pull/44#issuecomment-226211813 and further along the thread about tightening up the layout for the user data sidebar. We can use some of Matt's help on this.

**Comment by FrancescoSTL** [comment]
Current experience: <img width="1631" alt="user data example" src="https://cloud.githubusercontent.com/assets/9794516/16384841/5f0bea06-3c3f-11e6-8872-23dcfc8bc67d.png">

**Comment by ternstyles** [comment]
I am going to take a look at refining this a bit today. Don't think there is much need for any major changes, just some spacing here and there.

**Comment by ternstyles** [comment]
My recommendation for the import data side bar. This section can get heavy fast with all the info coming at you, especially with unpredictable link lengths. I think if we limit links to a single line we can keep things cleaner and easier to digest content wise.
![user data](https://cloud.githubusercontent.com/assets/20114656/16401420/59cfe1aa-3cb2-11e6-88e0-bc2c3ee6b0c3.png)

**Comment by fabiorios** [comment]
Where does the "Get Started" button lead to?

**Comment by FrancescoSTL** [comment]
@fabiorios currently, about:home

**Comment by FrancescoSTL** [comment]
So, I have thought of something that may be a bit better than a user import data sidebar. What if, instead of opening another sidebar, which seems kind of heavy with the current experience, we simply open up the new-tab page? We can run a pageMod on new-tab, just as we are doing on about:home for snippets, and add the additional copy, `"We've got your back, Firefox has already imported your prefs, etc..."`. This would allow us to use the current algorithm for showing "important" pages for users to see from their history, and also give the message that we've grabbed everything they love from their other browsers. We can also still grab history items and display them as well.

**Comment by chrismore** [comment]
@FrancescoSTL that's not a bad idea and I think we talked about it before. We could use the add-on to add a message to about:newtab like you mentioned. It would save from having to re-create similar logic.

**Comment by chrismore** [comment]
The only thing is that it only shows you your history and not bookmarks, but maybe that's not a huge issue.

**Comment by FrancescoSTL** [comment]
@chrismore we already have the logic built to grab bookmark data anyway, so we could still add it. We'd need new UX mockups I suppose, but for now, maybe I just work on adding the pagemod. It is much more lean than what we're currently doing. We can iterate on this in the future and modify the page further as time goes on, if we have time.

**Comment by chrismore** [comment]
@FrancescoSTL we are going to need to need to find a replace to put the "Undo browser import" button or link. Probably just a small link at the bottom.

**Comment by FrancescoSTL** [comment]
@chrismore that could work. We could do it under the added copy. I'll likely add the header and body copy from the snippet. This opens up the door to do a lot more things, design-wise, in the future. Maybe we want to minimize the amount of additional stuff we'd add to the page, however, just to keep some continuity in the experience they receive on new-tab. Also, I'll need to find a way to destroy the modification as soon as it is shown once.

**Comment by fabiorios** [comment]
I like this. Let's them get going right away. Currently with the panel we
are requiring them to close it before they can continue.

As long as we can deliver a message that we've imported their stuff, we are
fine not to show them specifics. They are going to see it right away, and
that's most important.

The undo can be a text link at the end of the message.

*Fabio Rios* | Firefox Product Marketing | frios@mozilla.com | IRC: frios

**Comment by FrancescoSTL** [comment]
@ternstyles per the conversation above, anything I should keep in mind style-wise? Would it be worth mocking up a design for the new about:new-tab layout? Sorry that we changed this so quickly!

**Comment by FrancescoSTL** [comment]
This thread will now be used to track progress on #189

**Comment by FrancescoSTL** [comment]
Removing p1 tag so that we know this isn't a task, just for tracking.

**Comment by ternstyles** [comment]
Not a big stray from what cmore posted in Slack, but here's what I am thinking for the First Run data import page. I've shown this here with only 2 rows of tiles, but I believe 3 always appear and a scroller is produced for smaller resolutions. The lower line 'Didn't want browser preferences...' would appear roughly 70px below the bottom of the last row of tiles.
![user data_first-run](https://cloud.githubusercontent.com/assets/20114656/16429526/40e16be4-3d45-11e6-97b5-982db7b613da.png)

**Comment by FrancescoSTL** [comment]
@ternstyles Do you know what font you were using for the mockup above?

**Comment by chrismore** [comment]
@ternstyles looks great!

**Comment by chrismore** [comment]
@ternstyles @FrancescoSTL looks like newtab tiles use font-family: Lucida Grande;

**Comment by ternstyles** [comment]
thanks for clarifying @chrismore. I wasn't aware myself. @FrancescoSTL I've updated the mockup using Lucida Grande.
![user data first run](https://cloud.githubusercontent.com/assets/20114656/16430794/75455aac-3d4b-11e6-9740-300a2ce2fb0a.png)

**Comment by chrismore** [comment]
No sidebar due to #189
