### ISSUE TITLE
Destroy Add-On Conditions

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#92]
There are two conditions at which point we want to "uninstall" the add-on:

1. If a user clicks the "No thanks" link on the /firstrun question modal
2. When the user has interacted with all 5 content sidebars as well as the final reward sidebar.

From what I have been able to determine, there is no uninstall function we can call so, my proposal is this. Each of the components we use, `Sidebar`, `ActionButton`, and `pageMod` have either a `destroy` or `dispose` function. Once this is called, the component will no longer function and, and interaction attempts with the component will fail.

Also, for the `ActionButton`, it will cause it to be removed from the toolbar. We can therefore essentially fake a complete uninstall by writing a `destroy` function that will `destroy/dispose` any of the components that are still active thus, rendering the add-on inactive and, other than it's physical footprint, uninstalled/disabled.

Thoughts?

**Comment by chrismore** [comment]
@schalkneethling Those are the right conditions, but there is also a 3rd one.

1) If a user clicks the "No thanks" link on the /firstrun quesiton modal

2) 2 weeks after content 6 sticker offer regardless if they have taken in

3) After 3 weeks of not using the Add-on 

These 3 conditions ensures that the add-on doesn't stick around in the chrome and the ActionButton is gone forever all users eventually.

@schalkneethling thoughts on this logic?

**Comment by FrancescoSTL** [comment]
Can be closed upon successful merge of #190

**Comment by FrancescoSTL** [comment]
Fixed in #190
