### ISSUE TITLE
Reduce add-on requests to AMO

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#95]
From 2 to 1 to reduce latency.

**Comment by schalkneethling** [comment]
@chrismore Can you expand a little on this? Looking at the code, it seems to only do one request:
https://github.com/mozilla/all-aboard/blob/master/index.js#L207

**Comment by FrancescoSTL** [comment]
@schalkneethling @chrismore ah, that was my fault. I forgot that we changed it to one request. We can still add the image files locally for a load of ~120kb per theme.

**Comment by FrancescoSTL** [comment]
^if latency is still an issue

**Comment by chrismore** [comment]
@FrancescoSTL let's not add the images locally for now. The add-on is already going to be big enough. If we worry about the latency, we could have a progress spinner while waiting for the theme to apply, but I am not sure if there is an event you could detect on when the theme finishes applying.
