### ISSUE TITLE
Update desktop notification copy and image

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#96]
* need new copy
* Need to ensure the Firefox logo is the icon and not the light bulb icon (https://github.com/mozilla/all-aboard/issues/66)

**Comment by FrancescoSTL** [comment]
https://github.com/mozilla/all-aboard/blob/3e626330226b15264339d82cb73e5edbb46e103a/index.js#L159

**Comment by chrismore** [comment]
Clarification:

Desktop notification icon: Firefox logo
Chrome Badge: Light bulb icon

**Comment by chrismore** [comment]
Actually, it looks like desktop notifications have two icons, the application itself from the OS and another icon to the right is custom. We should then make the notification have Firefox icon left (default) and Light bulb icon right.

**Comment by chrismore** [comment]
This issue may be deprecated by issue #66 if @schalkneethling just updates the png source directly since this notification already points to an icon that is also used in the chrome.

**Comment by FrancescoSTL** [comment]
@bniolet1 @chrismore Have we determined what the copy will be for the notification? We need both a title (currently `All Aboard`) and body (currently `You have a new message`).

**Comment by FrancescoSTL** [comment]
Seems this issue is duplicated in #66 and #135. Closing.
