### ISSUE TITLE
Add Adjust ADK attribution URLs for the mobile icons

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#98]
@bniolet1 can make us the two URLs and swap them out for the google play and app store links.

**Comment by bniolet1** [comment]
Android link:
http://mzl.la/1HKLL5H

iOS link:
https://mzl.la/1YtDCxH

**Comment by bniolet1** [comment]
These are the links above, but unshortened: 

Android
https://app.adjust.com/2uo1qc?campaign=inprod&adgroup=fdr_addon&creative=utilityandroid

iOS
https://app.adjust.com/2uo1qc?campaign=inprod&adgroup=fdr_addon&creative=utilityios&fallback=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fapple-store%2Fid989804926%3Fpt%3D373246%26ct%3Dadjust_tracker%26mt%3D8

**Comment by FrancescoSTL** [comment]
Fixed in #153
