### ISSUE TITLE
Reduce margin below header question on values track

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#99]
Make the margin above the answers to be equal to the margin below the answers. i.e. balance the margins above and below the radio button answers.

**Comment by FrancescoSTL** [comment]
<img width="321" alt="screen shot 2016-06-16 at 10 08 30 am" src="https://cloud.githubusercontent.com/assets/9794516/16111415/61e76388-33aa-11e6-8ac4-ee54a9cd74cc.png">

**Comment by FrancescoSTL** [comment]
Fixed in #106
